/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.EtudeConsommations;
import models.tables.records.EtudeConsommationsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Table stockant les données d'étude de consommations des bons de commande
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudeConsommationsDao extends DAOImpl<EtudeConsommationsRecord, models.tables.pojos.EtudeConsommations, Long> {

    /**
     * Create a new EtudeConsommationsDao without any configuration
     */
    public EtudeConsommationsDao() {
        super(EtudeConsommations.ETUDE_CONSOMMATIONS, models.tables.pojos.EtudeConsommations.class);
    }

    /**
     * Create a new EtudeConsommationsDao with an attached configuration
     */
    public EtudeConsommationsDao(Configuration configuration) {
        super(EtudeConsommations.ETUDE_CONSOMMATIONS, models.tables.pojos.EtudeConsommations.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.EtudeConsommations object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchById(Long... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.EtudeConsommations fetchOneById(Long value) {
        return fetchOne(EtudeConsommations.ETUDE_CONSOMMATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>numero_carnet IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByNumeroCarnet(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.NUMERO_CARNET, values);
    }

    /**
     * Fetch records that have <code>code_agent IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByCodeAgent(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CODE_AGENT, values);
    }

    /**
     * Fetch records that have <code>nom_prenoms IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByNomPrenoms(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.NOM_PRENOMS, values);
    }

    /**
     * Fetch records that have <code>agent IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByAgent(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.AGENT, values);
    }

    /**
     * Fetch records that have <code>conjoint IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByConjoint(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CONJOINT, values);
    }

    /**
     * Fetch records that have <code>enfants IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByEnfants(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.ENFANTS, values);
    }

    /**
     * Fetch records that have <code>pere IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByPere(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.PERE, values);
    }

    /**
     * Fetch records that have <code>mere IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByMere(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.MERE, values);
    }

    /**
     * Fetch records that have <code>salaire_base IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchBySalaireBase(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.SALAIRE_BASE, values);
    }

    /**
     * Fetch records that have <code>pourcentage_retenir IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByPourcentageRetenir(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.POURCENTAGE_RETENIR, values);
    }

    /**
     * Fetch records that have <code>retenue_mensuelle IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByRetenueMensuelle(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.RETENUE_MENSUELLE, values);
    }

    /**
     * Fetch records that have <code>credit_annuel IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByCreditAnnuel(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CREDIT_ANNUEL, values);
    }

    /**
     * Fetch records that have <code>credit_annuel_x2 IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByCreditAnnuelX2(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CREDIT_ANNUEL_X2, values);
    }

    /**
     * Fetch records that have <code>consommation_bons IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByConsommationBons(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CONSOMMATION_BONS, values);
    }

    /**
     * Fetch records that have <code>consommation_pc IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByConsommationPc(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.CONSOMMATION_PC, values);
    }

    /**
     * Fetch records that have <code>remboursement IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByRemboursement(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.REMBOURSEMENT, values);
    }

    /**
     * Fetch records that have <code>total_consommation IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByTotalConsommation(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.TOTAL_CONSOMMATION, values);
    }

    /**
     * Fetch records that have <code>solde_1 IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchBySolde_1(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.SOLDE_1, values);
    }

    /**
     * Fetch records that have <code>solde_2 IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchBySolde_2(BigDecimal... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.SOLDE_2, values);
    }

    /**
     * Fetch records that have <code>statut_avertissement IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByStatutAvertissement(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.STATUT_AVERTISSEMENT, values);
    }

    /**
     * Fetch records that have <code>statut_suspension IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByStatutSuspension(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.STATUT_SUSPENSION, values);
    }

    /**
     * Fetch records that have <code>fichier_source IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByFichierSource(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.FICHIER_SOURCE, values);
    }

    /**
     * Fetch records that have <code>date_import IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByDateImport(Timestamp... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.DATE_IMPORT, values);
    }

    /**
     * Fetch records that have <code>utilisateur_import IN (values)</code>
     */
    public List<models.tables.pojos.EtudeConsommations> fetchByUtilisateurImport(String... values) {
        return fetch(EtudeConsommations.ETUDE_CONSOMMATIONS.UTILISATEUR_IMPORT, values);
    }
}
