/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.tables.OtpMessage;
import models.tables.records.OtpMessageRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtpMessageDao extends DAOImpl<OtpMessageRecord, models.tables.pojos.OtpMessage, Long> {

    /**
     * Create a new OtpMessageDao without any configuration
     */
    public OtpMessageDao() {
        super(OtpMessage.OTP_MESSAGE, models.tables.pojos.OtpMessage.class);
    }

    /**
     * Create a new OtpMessageDao with an attached configuration
     */
    public OtpMessageDao(Configuration configuration) {
        super(OtpMessage.OTP_MESSAGE, models.tables.pojos.OtpMessage.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.tables.pojos.OtpMessage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchById(Long... values) {
        return fetch(OtpMessage.OTP_MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.OtpMessage fetchOneById(Long value) {
        return fetchOne(OtpMessage.OTP_MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByPhone(String... values) {
        return fetch(OtpMessage.OTP_MESSAGE.PHONE, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByCode(String... values) {
        return fetch(OtpMessage.OTP_MESSAGE.CODE, values);
    }

    /**
     * Fetch records that have <code>message_texte IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByMessageTexte(String... values) {
        return fetch(OtpMessage.OTP_MESSAGE.MESSAGE_TEXTE, values);
    }

    /**
     * Fetch records that have <code>bon_commande IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByBonCommande(Long... values) {
        return fetch(OtpMessage.OTP_MESSAGE.BON_COMMANDE, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByCreatedAt(Timestamp... values) {
        return fetch(OtpMessage.OTP_MESSAGE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>expires_at IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByExpiresAt(Timestamp... values) {
        return fetch(OtpMessage.OTP_MESSAGE.EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>is_used IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByIsUsed(Boolean... values) {
        return fetch(OtpMessage.OTP_MESSAGE.IS_USED, values);
    }

    /**
     * Fetch records that have <code>is_sent IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByIsSent(Boolean... values) {
        return fetch(OtpMessage.OTP_MESSAGE.IS_SENT, values);
    }

    /**
     * Fetch records that have <code>sent_response IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchBySentResponse(String... values) {
        return fetch(OtpMessage.OTP_MESSAGE.SENT_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>attempt_count IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByAttemptCount(Integer... values) {
        return fetch(OtpMessage.OTP_MESSAGE.ATTEMPT_COUNT, values);
    }

    /**
     * Fetch records that have <code>context IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByContext(String... values) {
        return fetch(OtpMessage.OTP_MESSAGE.CONTEXT, values);
    }

    /**
     * Fetch records that have <code>montant_bon IN (values)</code>
     */
    public List<models.tables.pojos.OtpMessage> fetchByMontantBon(Long... values) {
        return fetch(OtpMessage.OTP_MESSAGE.MONTANT_BON, values);
    }
}
