/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.EtudeConsommations;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Table stockant les données d'étude de consommations des bons de commande
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudeConsommationsRecord extends UpdatableRecordImpl<EtudeConsommationsRecord> {

    private static final long serialVersionUID = -1862782084;

    /**
     * Setter for <code>public.etude_consommations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.etude_consommations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.etude_consommations.numero_carnet</code>. Numéro du carnet de l'adhérent
     */
    public void setNumeroCarnet(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.etude_consommations.numero_carnet</code>. Numéro du carnet de l'adhérent
     */
    public String getNumeroCarnet() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.etude_consommations.code_agent</code>. Code unique de l'agent
     */
    public void setCodeAgent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.etude_consommations.code_agent</code>. Code unique de l'agent
     */
    public String getCodeAgent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.etude_consommations.nom_prenoms</code>.
     */
    public void setNomPrenoms(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.etude_consommations.nom_prenoms</code>.
     */
    public String getNomPrenoms() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.etude_consommations.agent</code>.
     */
    public void setAgent(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.etude_consommations.agent</code>.
     */
    public BigDecimal getAgent() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.etude_consommations.conjoint</code>.
     */
    public void setConjoint(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.etude_consommations.conjoint</code>.
     */
    public BigDecimal getConjoint() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.etude_consommations.enfants</code>.
     */
    public void setEnfants(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.etude_consommations.enfants</code>.
     */
    public BigDecimal getEnfants() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.etude_consommations.pere</code>.
     */
    public void setPere(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.etude_consommations.pere</code>.
     */
    public BigDecimal getPere() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.etude_consommations.mere</code>.
     */
    public void setMere(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.etude_consommations.mere</code>.
     */
    public BigDecimal getMere() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.etude_consommations.salaire_base</code>. Salaire de base de l'agent
     */
    public void setSalaireBase(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.etude_consommations.salaire_base</code>. Salaire de base de l'agent
     */
    public BigDecimal getSalaireBase() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.etude_consommations.pourcentage_retenir</code>.
     */
    public void setPourcentageRetenir(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.etude_consommations.pourcentage_retenir</code>.
     */
    public BigDecimal getPourcentageRetenir() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.etude_consommations.retenue_mensuelle</code>.
     */
    public void setRetenueMensuelle(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.etude_consommations.retenue_mensuelle</code>.
     */
    public BigDecimal getRetenueMensuelle() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.etude_consommations.credit_annuel</code>.
     */
    public void setCreditAnnuel(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.etude_consommations.credit_annuel</code>.
     */
    public BigDecimal getCreditAnnuel() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.etude_consommations.credit_annuel_x2</code>.
     */
    public void setCreditAnnuelX2(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.etude_consommations.credit_annuel_x2</code>.
     */
    public BigDecimal getCreditAnnuelX2() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>public.etude_consommations.consommation_bons</code>.
     */
    public void setConsommationBons(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.etude_consommations.consommation_bons</code>.
     */
    public BigDecimal getConsommationBons() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>public.etude_consommations.consommation_pc</code>.
     */
    public void setConsommationPc(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.etude_consommations.consommation_pc</code>.
     */
    public BigDecimal getConsommationPc() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>public.etude_consommations.remboursement</code>.
     */
    public void setRemboursement(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.etude_consommations.remboursement</code>.
     */
    public BigDecimal getRemboursement() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>public.etude_consommations.total_consommation</code>. Total des consommations (Bons + PC + Remboursement)
     */
    public void setTotalConsommation(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.etude_consommations.total_consommation</code>. Total des consommations (Bons + PC + Remboursement)
     */
    public BigDecimal getTotalConsommation() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>public.etude_consommations.solde_1</code>.
     */
    public void setSolde_1(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.etude_consommations.solde_1</code>.
     */
    public BigDecimal getSolde_1() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>public.etude_consommations.solde_2</code>.
     */
    public void setSolde_2(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.etude_consommations.solde_2</code>.
     */
    public BigDecimal getSolde_2() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.etude_consommations.statut_avertissement</code>. Statut d'avertissement (AVERTIS, etc.)
     */
    public void setStatutAvertissement(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.etude_consommations.statut_avertissement</code>. Statut d'avertissement (AVERTIS, etc.)
     */
    public String getStatutAvertissement() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.etude_consommations.statut_suspension</code>. Statut de suspension (SUSPENDUS, etc.)
     */
    public void setStatutSuspension(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.etude_consommations.statut_suspension</code>. Statut de suspension (SUSPENDUS, etc.)
     */
    public String getStatutSuspension() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.etude_consommations.fichier_source</code>.
     */
    public void setFichierSource(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.etude_consommations.fichier_source</code>.
     */
    public String getFichierSource() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.etude_consommations.date_import</code>.
     */
    public void setDateImport(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.etude_consommations.date_import</code>.
     */
    public Timestamp getDateImport() {
        return (Timestamp) get(23);
    }

    /**
     * Setter for <code>public.etude_consommations.utilisateur_import</code>.
     */
    public void setUtilisateurImport(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.etude_consommations.utilisateur_import</code>.
     */
    public String getUtilisateurImport() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EtudeConsommationsRecord
     */
    public EtudeConsommationsRecord() {
        super(EtudeConsommations.ETUDE_CONSOMMATIONS);
    }

    /**
     * Create a detached, initialised EtudeConsommationsRecord
     */
    public EtudeConsommationsRecord(Long id, String numeroCarnet, String codeAgent, String nomPrenoms, BigDecimal agent, BigDecimal conjoint, BigDecimal enfants, BigDecimal pere, BigDecimal mere, BigDecimal salaireBase, BigDecimal pourcentageRetenir, BigDecimal retenueMensuelle, BigDecimal creditAnnuel, BigDecimal creditAnnuelX2, BigDecimal consommationBons, BigDecimal consommationPc, BigDecimal remboursement, BigDecimal totalConsommation, BigDecimal solde_1, BigDecimal solde_2, String statutAvertissement, String statutSuspension, String fichierSource, Timestamp dateImport, String utilisateurImport) {
        super(EtudeConsommations.ETUDE_CONSOMMATIONS);

        set(0, id);
        set(1, numeroCarnet);
        set(2, codeAgent);
        set(3, nomPrenoms);
        set(4, agent);
        set(5, conjoint);
        set(6, enfants);
        set(7, pere);
        set(8, mere);
        set(9, salaireBase);
        set(10, pourcentageRetenir);
        set(11, retenueMensuelle);
        set(12, creditAnnuel);
        set(13, creditAnnuelX2);
        set(14, consommationBons);
        set(15, consommationPc);
        set(16, remboursement);
        set(17, totalConsommation);
        set(18, solde_1);
        set(19, solde_2);
        set(20, statutAvertissement);
        set(21, statutSuspension);
        set(22, fichierSource);
        set(23, dateImport);
        set(24, utilisateurImport);
    }
}
