/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import models.tables.Notification;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends TableRecordImpl<NotificationRecord> implements Record7<Long, Long, String, String, String, OffsetDateTime, String> {

    private static final long serialVersionUID = -1942329250;

    /**
     * Setter for <code>public.notification.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notification.adherent</code>.
     */
    public void setAdherent(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification.adherent</code>.
     */
    public Long getAdherent() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.notification.num_tel</code>.
     */
    public void setNumTel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification.num_tel</code>.
     */
    public String getNumTel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notification.num_bon</code>.
     */
    public void setNumBon(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification.num_bon</code>.
     */
    public String getNumBon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.notification.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.notification.when_done</code>.
     */
    public void setWhenDone(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notification.when_done</code>.
     */
    public OffsetDateTime getWhenDone() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.notification.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.notification.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, OffsetDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, OffsetDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Notification.NOTIFICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Notification.NOTIFICATION.ADHERENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Notification.NOTIFICATION.NUM_TEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Notification.NOTIFICATION.NUM_BON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Notification.NOTIFICATION.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return Notification.NOTIFICATION.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Notification.NOTIFICATION.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNumBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNumBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value2(Long value) {
        setAdherent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value3(String value) {
        setNumTel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value4(String value) {
        setNumBon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value6(OffsetDateTime value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value7(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord values(Long value1, Long value2, String value3, String value4, String value5, OffsetDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Long id, Long adherent, String numTel, String numBon, String message, OffsetDateTime whenDone, String whoDone) {
        super(Notification.NOTIFICATION);

        set(0, id);
        set(1, adherent);
        set(2, numTel);
        set(3, numBon);
        set(4, message);
        set(5, whenDone);
        set(6, whoDone);
    }
}
