/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.OtpMessage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtpMessageRecord extends UpdatableRecordImpl<OtpMessageRecord> implements Record12<Long, String, String, String, Long, Timestamp, Timestamp, Boolean, Boolean, String, Integer, String> {

    private static final long serialVersionUID = 393013402;

    /**
     * Setter for <code>public.otp_message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.otp_message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.otp_message.phone</code>.
     */
    public void setPhone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.otp_message.phone</code>.
     */
    public String getPhone() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.otp_message.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.otp_message.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.otp_message.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.otp_message.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.otp_message.bon_commande</code>.
     */
    public void setBonCommande(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.otp_message.bon_commande</code>.
     */
    public Long getBonCommande() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.otp_message.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.otp_message.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.otp_message.expires_at</code>.
     */
    public void setExpiresAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.otp_message.expires_at</code>.
     */
    public Timestamp getExpiresAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.otp_message.is_used</code>.
     */
    public void setIsUsed(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.otp_message.is_used</code>.
     */
    public Boolean getIsUsed() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.otp_message.is_sent</code>.
     */
    public void setIsSent(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.otp_message.is_sent</code>.
     */
    public Boolean getIsSent() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.otp_message.sent_response</code>.
     */
    public void setSentResponse(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.otp_message.sent_response</code>.
     */
    public String getSentResponse() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.otp_message.attempt_count</code>.
     */
    public void setAttemptCount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.otp_message.attempt_count</code>.
     */
    public Integer getAttemptCount() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.otp_message.context</code>.
     */
    public void setContext(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.otp_message.context</code>.
     */
    public String getContext() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, Long, Timestamp, Timestamp, Boolean, Boolean, String, Integer, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, Long, Timestamp, Timestamp, Boolean, Boolean, String, Integer, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OtpMessage.OTP_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OtpMessage.OTP_MESSAGE.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OtpMessage.OTP_MESSAGE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OtpMessage.OTP_MESSAGE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return OtpMessage.OTP_MESSAGE.BON_COMMANDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return OtpMessage.OTP_MESSAGE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return OtpMessage.OTP_MESSAGE.EXPIRES_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return OtpMessage.OTP_MESSAGE.IS_USED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return OtpMessage.OTP_MESSAGE.IS_SENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return OtpMessage.OTP_MESSAGE.SENT_RESPONSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return OtpMessage.OTP_MESSAGE.ATTEMPT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return OtpMessage.OTP_MESSAGE.CONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getBonCommande();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getIsUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSentResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getAttemptCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getBonCommande();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getIsUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSentResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getAttemptCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value2(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value3(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value5(Long value) {
        setBonCommande(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value7(Timestamp value) {
        setExpiresAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value8(Boolean value) {
        setIsUsed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value9(Boolean value) {
        setIsSent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value10(String value) {
        setSentResponse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value11(Integer value) {
        setAttemptCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord value12(String value) {
        setContext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessageRecord values(Long value1, String value2, String value3, String value4, Long value5, Timestamp value6, Timestamp value7, Boolean value8, Boolean value9, String value10, Integer value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtpMessageRecord
     */
    public OtpMessageRecord() {
        super(OtpMessage.OTP_MESSAGE);
    }

    /**
     * Create a detached, initialised OtpMessageRecord
     */
    public OtpMessageRecord(Long id, String phone, String code, String message, Long bonCommande, Timestamp createdAt, Timestamp expiresAt, Boolean isUsed, Boolean isSent, String sentResponse, Integer attemptCount, String context) {
        super(OtpMessage.OTP_MESSAGE);

        set(0, id);
        set(1, phone);
        set(2, code);
        set(3, message);
        set(4, bonCommande);
        set(5, createdAt);
        set(6, expiresAt);
        set(7, isUsed);
        set(8, isSent);
        set(9, sentResponse);
        set(10, attemptCount);
        set(11, context);
    }
}
