/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Reglement;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReglementRecord extends UpdatableRecordImpl<ReglementRecord> implements Record15<Long, Long, String, Long, Timestamp, String, Timestamp, Boolean, Long, Long, String, String, String, Boolean, Timestamp> {

    private static final long serialVersionUID = 980822527;

    /**
     * Setter for <code>public.reglement.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reglement.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reglement.adherent</code>.
     */
    public void setAdherent(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reglement.adherent</code>.
     */
    public Long getAdherent() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.reglement.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reglement.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.reglement.structure</code>.
     */
    public void setStructure(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reglement.structure</code>.
     */
    public Long getStructure() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.reglement.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.reglement.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.reglement.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.reglement.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.reglement.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.reglement.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.reglement.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.reglement.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.reglement.type_prestation</code>.
     */
    public void setTypePrestation(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.reglement.type_prestation</code>.
     */
    public Long getTypePrestation() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.reglement.ayant_droit</code>.
     */
    public void setAyantDroit(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.reglement.ayant_droit</code>.
     */
    public Long getAyantDroit() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.reglement.structure_emettrice_rembourssement</code>.
     */
    public void setStructureEmettriceRembourssement(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.reglement.structure_emettrice_rembourssement</code>.
     */
    public String getStructureEmettriceRembourssement() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.reglement.tel_structure_emettrice</code>.
     */
    public void setTelStructureEmettrice(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.reglement.tel_structure_emettrice</code>.
     */
    public String getTelStructureEmettrice() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.reglement.num_bon</code>.
     */
    public void setNumBon(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.reglement.num_bon</code>.
     */
    public String getNumBon() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.reglement.is_confirmed_bon</code>.
     */
    public void setIsConfirmedBon(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.reglement.is_confirmed_bon</code>.
     */
    public Boolean getIsConfirmedBon() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.reglement.when_confirmed_bon</code>.
     */
    public void setWhenConfirmedBon(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.reglement.when_confirmed_bon</code>.
     */
    public Timestamp getWhenConfirmedBon() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, Long, String, Long, Timestamp, String, Timestamp, Boolean, Long, Long, String, String, String, Boolean, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, Long, String, Long, Timestamp, String, Timestamp, Boolean, Long, Long, String, String, String, Boolean, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Reglement.REGLEMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Reglement.REGLEMENT.ADHERENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Reglement.REGLEMENT.REF_FACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Reglement.REGLEMENT.STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Reglement.REGLEMENT.DATE_PAYEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Reglement.REGLEMENT.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Reglement.REGLEMENT.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Reglement.REGLEMENT.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Reglement.REGLEMENT.TYPE_PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Reglement.REGLEMENT.AYANT_DROIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Reglement.REGLEMENT.STRUCTURE_EMETTRICE_REMBOURSSEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Reglement.REGLEMENT.TEL_STRUCTURE_EMETTRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Reglement.REGLEMENT.NUM_BON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return Reglement.REGLEMENT.IS_CONFIRMED_BON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return Reglement.REGLEMENT.WHEN_CONFIRMED_BON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getTypePrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getAyantDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getStructureEmettriceRembourssement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTelStructureEmettrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getNumBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getIsConfirmedBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getWhenConfirmedBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAdherent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getTypePrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getAyantDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStructureEmettriceRembourssement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTelStructureEmettrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getNumBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getIsConfirmedBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getWhenConfirmedBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value2(Long value) {
        setAdherent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value3(String value) {
        setRefFacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value4(Long value) {
        setStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value5(Timestamp value) {
        setDatePayement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value6(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value7(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value8(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value9(Long value) {
        setTypePrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value10(Long value) {
        setAyantDroit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value11(String value) {
        setStructureEmettriceRembourssement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value12(String value) {
        setTelStructureEmettrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value13(String value) {
        setNumBon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value14(Boolean value) {
        setIsConfirmedBon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord value15(Timestamp value) {
        setWhenConfirmedBon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReglementRecord values(Long value1, Long value2, String value3, Long value4, Timestamp value5, String value6, Timestamp value7, Boolean value8, Long value9, Long value10, String value11, String value12, String value13, Boolean value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReglementRecord
     */
    public ReglementRecord() {
        super(Reglement.REGLEMENT);
    }

    /**
     * Create a detached, initialised ReglementRecord
     */
    public ReglementRecord(Long id, Long adherent, String refFacture, Long structure, Timestamp datePayement, String whoDone, Timestamp whenDone, Boolean onDeleted, Long typePrestation, Long ayantDroit, String structureEmettriceRembourssement, String telStructureEmettrice, String numBon, Boolean isConfirmedBon, Timestamp whenConfirmedBon) {
        super(Reglement.REGLEMENT);

        set(0, id);
        set(1, adherent);
        set(2, refFacture);
        set(3, structure);
        set(4, datePayement);
        set(5, whoDone);
        set(6, whenDone);
        set(7, onDeleted);
        set(8, typePrestation);
        set(9, ayantDroit);
        set(10, structureEmettriceRembourssement);
        set(11, telStructureEmettrice);
        set(12, numBon);
        set(13, isConfirmedBon);
        set(14, whenConfirmedBon);
    }
}
