/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.TypePrestation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePrestationRecord extends UpdatableRecordImpl<TypePrestationRecord> implements Record7<Long, String, String, Boolean, String, String, String> {

    private static final long serialVersionUID = -1936445866;

    /**
     * Setter for <code>public.type_prestation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.type_prestation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.type_prestation.prestation</code>.
     */
    public void setPrestation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.type_prestation.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.type_prestation.couverture</code>.
     */
    public void setCouverture(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.type_prestation.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.type_prestation.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.type_prestation.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.type_prestation.taux_public</code>.
     */
    public void setTauxPublic(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.type_prestation.taux_public</code>.
     */
    public String getTauxPublic() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.type_prestation.taux_prive</code>.
     */
    public void setTauxPrive(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.type_prestation.taux_prive</code>.
     */
    public String getTauxPrive() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.type_prestation.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.type_prestation.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Boolean, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Boolean, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TypePrestation.TYPE_PRESTATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TypePrestation.TYPE_PRESTATION.PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TypePrestation.TYPE_PRESTATION.COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TypePrestation.TYPE_PRESTATION.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TypePrestation.TYPE_PRESTATION.TAUX_PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TypePrestation.TYPE_PRESTATION.TAUX_PRIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TypePrestation.TYPE_PRESTATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTauxPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTauxPrive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTauxPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTauxPrive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value2(String value) {
        setPrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value3(String value) {
        setCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value4(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value5(String value) {
        setTauxPublic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value6(String value) {
        setTauxPrive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePrestationRecord values(Long value1, String value2, String value3, Boolean value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TypePrestationRecord
     */
    public TypePrestationRecord() {
        super(TypePrestation.TYPE_PRESTATION);
    }

    /**
     * Create a detached, initialised TypePrestationRecord
     */
    public TypePrestationRecord(Long id, String prestation, String couverture, Boolean onDeleted, String tauxPublic, String tauxPrive, String type) {
        super(TypePrestation.TYPE_PRESTATION);

        set(0, id);
        set(1, prestation);
        set(2, couverture);
        set(3, onDeleted);
        set(4, tauxPublic);
        set(5, tauxPrive);
        set(6, type);
    }
}
