/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record11<Long, String, String, Boolean, String, String, String, Boolean, String, Timestamp, Long> {

    private static final long serialVersionUID = -1094686107;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.login</code>.
     */
    public void setLogin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.droit</code>.
     */
    public void setDroit(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.droit</code>.
     */
    public String getDroit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.etat</code>.
     */
    public void setEtat(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.etat</code>.
     */
    public Boolean getEtat() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.users.passe</code>.
     */
    public void setPasse(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.passe</code>.
     */
    public String getPasse() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.nom_prenom</code>.
     */
    public void setNomPrenom(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.nom_prenom</code>.
     */
    public String getNomPrenom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.photo</code>.
     */
    public void setPhoto(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.photo</code>.
     */
    public String getPhoto() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.connect_first</code>.
     */
    public void setConnectFirst(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.connect_first</code>.
     */
    public Boolean getConnectFirst() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.users.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.users.region_code</code>.
     */
    public void setRegionCode(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.region_code</code>.
     */
    public Long getRegionCode() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Boolean, String, String, String, Boolean, String, Timestamp, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Boolean, String, String, String, Boolean, String, Timestamp, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Users.USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.DROIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Users.USERS.ETAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.PASSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.NOM_PRENOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Users.USERS.CONNECT_FIRST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Users.USERS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Users.USERS.REGION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEtat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getConnectFirst();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getRegionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEtat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getConnectFirst();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getRegionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setDroit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Boolean value) {
        setEtat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setPasse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setNomPrenom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Boolean value) {
        setConnectFirst(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(Long value) {
        setRegionCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(Long value1, String value2, String value3, Boolean value4, String value5, String value6, String value7, Boolean value8, String value9, Timestamp value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String login, String droit, Boolean etat, String passe, String nomPrenom, String photo, Boolean connectFirst, String whoDone, Timestamp whenDone, Long regionCode) {
        super(Users.USERS);

        set(0, id);
        set(1, login);
        set(2, droit);
        set(3, etat);
        set(4, passe);
        set(5, nomPrenom);
        set(6, photo);
        set(7, connectFirst);
        set(8, whoDone);
        set(9, whenDone);
        set(10, regionCode);
    }
}
