/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VAdherentBadges;

import org.jooq.Field;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentBadgesRecord extends TableRecordImpl<VAdherentBadgesRecord> implements Record22<Long, String, String, String, String, String, String, String, Timestamp, Double, Timestamp, Double, String, Timestamp, String, Boolean, Boolean, Boolean, String, String, String, String> {

    private static final long serialVersionUID = -1208771718;

    /**
     * Setter for <code>public.v_adherent_badges.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_adherent_badges.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_adherent_badges.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_adherent_badges.sexe</code>.
     */
    public void setSexe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.sexe</code>.
     */
    public String getSexe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_adherent_badges.matricule</code>.
     */
    public void setMatricule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_adherent_badges.categorie</code>.
     */
    public void setCategorie(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_adherent_badges.fonction</code>.
     */
    public void setFonction(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.fonction</code>.
     */
    public String getFonction() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_adherent_badges.structure_sigle</code>.
     */
    public void setStructureSigle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.structure_sigle</code>.
     */
    public String getStructureSigle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_adherent_badges.date_naiss</code>.
     */
    public void setDateNaiss(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.date_naiss</code>.
     */
    public Timestamp getDateNaiss() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.v_adherent_badges.age</code>.
     */
    public void setAge(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.age</code>.
     */
    public Double getAge() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.v_adherent_badges.date_prise_service</code>.
     */
    public void setDatePriseService(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.date_prise_service</code>.
     */
    public Timestamp getDatePriseService() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.v_adherent_badges.anciennete</code>.
     */
    public void setAnciennete(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.anciennete</code>.
     */
    public Double getAnciennete() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.v_adherent_badges.picture</code>.
     */
    public void setPicture(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.picture</code>.
     */
    public String getPicture() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_adherent_badges.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>public.v_adherent_badges.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_adherent_badges.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>public.v_adherent_badges.is_ok_for_printing</code>.
     */
    public void setIsOkForPrinting(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.is_ok_for_printing</code>.
     */
    public Boolean getIsOkForPrinting() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.v_adherent_badges.is_member</code>.
     */
    public void setIsMember(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.is_member</code>.
     */
    public Boolean getIsMember() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.v_adherent_badges.direction</code>.
     */
    public void setDirection(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.direction</code>.
     */
    public String getDirection() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_adherent_badges.division</code>.
     */
    public void setDivision(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.division</code>.
     */
    public String getDivision() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.v_adherent_badges.service</code>.
     */
    public void setService(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.service</code>.
     */
    public String getService() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.v_adherent_badges.telephone</code>.
     */
    public void setTelephone(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_adherent_badges.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, String, String, String, String, String, String, String, Timestamp, Double, Timestamp, Double, String, Timestamp, String, Boolean, Boolean, Boolean, String, String, String, String> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, String, String, String, String, String, String, String, Timestamp, Double, Timestamp, Double, String, Timestamp, String, Boolean, Boolean, Boolean, String, String, String, String> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VAdherentBadges.V_ADHERENT_BADGES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VAdherentBadges.V_ADHERENT_BADGES.NOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VAdherentBadges.V_ADHERENT_BADGES.PRENOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VAdherentBadges.V_ADHERENT_BADGES.SEXE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VAdherentBadges.V_ADHERENT_BADGES.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VAdherentBadges.V_ADHERENT_BADGES.CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VAdherentBadges.V_ADHERENT_BADGES.FONCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VAdherentBadges.V_ADHERENT_BADGES.STRUCTURE_SIGLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return VAdherentBadges.V_ADHERENT_BADGES.DATE_NAISS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return VAdherentBadges.V_ADHERENT_BADGES.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return VAdherentBadges.V_ADHERENT_BADGES.DATE_PRISE_SERVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return VAdherentBadges.V_ADHERENT_BADGES.ANCIENNETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VAdherentBadges.V_ADHERENT_BADGES.PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return VAdherentBadges.V_ADHERENT_BADGES.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VAdherentBadges.V_ADHERENT_BADGES.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return VAdherentBadges.V_ADHERENT_BADGES.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return VAdherentBadges.V_ADHERENT_BADGES.IS_OK_FOR_PRINTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field18() {
        return VAdherentBadges.V_ADHERENT_BADGES.IS_MEMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return VAdherentBadges.V_ADHERENT_BADGES.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return VAdherentBadges.V_ADHERENT_BADGES.DIVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return VAdherentBadges.V_ADHERENT_BADGES.SERVICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field22() {
        return VAdherentBadges.V_ADHERENT_BADGES.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFonction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStructureSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getDatePriseService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component12() {
        return getAnciennete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component16() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getIsOkForPrinting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component18() {
        return getIsMember();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getDivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component21() {
        return getService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component22() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSexe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFonction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStructureSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getDatePriseService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getAnciennete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getIsOkForPrinting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value18() {
        return getIsMember();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getDivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getService();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value22() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value2(String value) {
        setNomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value3(String value) {
        setPrenomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value4(String value) {
        setSexe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value5(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value6(String value) {
        setCategorie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value7(String value) {
        setFonction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value8(String value) {
        setStructureSigle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value9(Timestamp value) {
        setDateNaiss(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value10(Double value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value11(Timestamp value) {
        setDatePriseService(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value12(Double value) {
        setAnciennete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value13(String value) {
        setPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value14(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value15(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value16(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value17(Boolean value) {
        setIsOkForPrinting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value18(Boolean value) {
        setIsMember(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value19(String value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value20(String value) {
        setDivision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value21(String value) {
        setService(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord value22(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadgesRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9, Double value10, Timestamp value11, Double value12, String value13, Timestamp value14, String value15, Boolean value16, Boolean value17, Boolean value18, String value19, String value20, String value21, String value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAdherentBadgesRecord
     */
    public VAdherentBadgesRecord() {
        super(VAdherentBadges.V_ADHERENT_BADGES);
    }

    /**
     * Create a detached, initialised VAdherentBadgesRecord
     */
    public VAdherentBadgesRecord(Long id, String nomAd, String prenomAd, String sexe, String matricule, String categorie, String fonction, String structureSigle, Timestamp dateNaiss, Double age, Timestamp datePriseService, Double anciennete, String picture, Timestamp whenDone, String whoDone, Boolean onDeleted, Boolean isOkForPrinting, Boolean isMember, String direction, String division, String service, String telephone) {
        super(VAdherentBadges.V_ADHERENT_BADGES);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, sexe);
        set(4, matricule);
        set(5, categorie);
        set(6, fonction);
        set(7, structureSigle);
        set(8, dateNaiss);
        set(9, age);
        set(10, datePriseService);
        set(11, anciennete);
        set(12, picture);
        set(13, whenDone);
        set(14, whoDone);
        set(15, onDeleted);
        set(16, isOkForPrinting);
        set(17, isMember);
        set(18, direction);
        set(19, division);
        set(20, service);
        set(21, telephone);
    }
}
