/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VAdherent;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentRecord extends TableRecordImpl<VAdherentRecord> {

    private static final long serialVersionUID = -1138274763;

    /**
     * Setter for <code>public.v_adherent.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_adherent.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_adherent.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_adherent.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_adherent.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_adherent.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_adherent.sexe</code>.
     */
    public void setSexe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_adherent.sexe</code>.
     */
    public String getSexe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_adherent.matricule</code>.
     */
    public void setMatricule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_adherent.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_adherent.code_carnet</code>.
     */
    public void setCodeCarnet(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_adherent.code_carnet</code>.
     */
    public String getCodeCarnet() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_adherent.categorie</code>.
     */
    public void setCategorie(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_adherent.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_adherent.fonction</code>.
     */
    public void setFonction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_adherent.fonction</code>.
     */
    public String getFonction() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_adherent.structure_sigle</code>.
     */
    public void setStructureSigle(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_adherent.structure_sigle</code>.
     */
    public String getStructureSigle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_adherent.date_naiss</code>.
     */
    public void setDateNaiss(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_adherent.date_naiss</code>.
     */
    public Timestamp getDateNaiss() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.v_adherent.age</code>.
     */
    public void setAge(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_adherent.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.v_adherent.date_prise_service</code>.
     */
    public void setDatePriseService(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_adherent.date_prise_service</code>.
     */
    public Timestamp getDatePriseService() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.v_adherent.anciennete</code>.
     */
    public void setAnciennete(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_adherent.anciennete</code>.
     */
    public Integer getAnciennete() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.v_adherent.salaire_net</code>.
     */
    public void setSalaireNet(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_adherent.salaire_net</code>.
     */
    public Long getSalaireNet() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.v_adherent.pourcentage_total_retenue</code>.
     */
    public void setPourcentageTotalRetenue(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_adherent.pourcentage_total_retenue</code>.
     */
    public Double getPourcentageTotalRetenue() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.v_adherent.total_cotisation_agent</code>.
     */
    public void setTotalCotisationAgent(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_adherent.total_cotisation_agent</code>.
     */
    public Double getTotalCotisationAgent() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.v_adherent.total_credit_annuelle</code>.
     */
    public void setTotalCreditAnnuelle(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_adherent.total_credit_annuelle</code>.
     */
    public Double getTotalCreditAnnuelle() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.v_adherent.total_credit_a_consomer</code>.
     */
    public void setTotalCreditAConsomer(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_adherent.total_credit_a_consomer</code>.
     */
    public Double getTotalCreditAConsomer() {
        return (Double) get(17);
    }

    /**
     * Setter for <code>public.v_adherent.montant_total_brute</code>.
     */
    public void setMontantTotalBrute(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_adherent.montant_total_brute</code>.
     */
    public BigDecimal getMontantTotalBrute() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>public.v_adherent.montant_reglement_couvert</code>.
     */
    public void setMontantReglementCouvert(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_adherent.montant_reglement_couvert</code>.
     */
    public BigDecimal getMontantReglementCouvert() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.v_adherent.montant_payer</code>.
     */
    public void setMontantPayer(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_adherent.montant_payer</code>.
     */
    public BigDecimal getMontantPayer() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>public.v_adherent.picture</code>.
     */
    public void setPicture(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_adherent.picture</code>.
     */
    public String getPicture() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.v_adherent.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_adherent.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>public.v_adherent.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.v_adherent.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.v_adherent.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.v_adherent.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>public.v_adherent.direction</code>.
     */
    public void setDirection(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.v_adherent.direction</code>.
     */
    public String getDirection() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.v_adherent.division</code>.
     */
    public void setDivision(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.v_adherent.division</code>.
     */
    public String getDivision() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.v_adherent.service</code>.
     */
    public void setService(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.v_adherent.service</code>.
     */
    public String getService() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.v_adherent.telephone</code>.
     */
    public void setTelephone(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.v_adherent.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(28);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAdherentRecord
     */
    public VAdherentRecord() {
        super(VAdherent.V_ADHERENT);
    }

    /**
     * Create a detached, initialised VAdherentRecord
     */
    public VAdherentRecord(Long id, String nomAd, String prenomAd, String sexe, String matricule, String codeCarnet, String categorie, String fonction, String structureSigle, Timestamp dateNaiss, Integer age, Timestamp datePriseService, Integer anciennete, Long salaireNet, Double pourcentageTotalRetenue, Double totalCotisationAgent, Double totalCreditAnnuelle, Double totalCreditAConsomer, BigDecimal montantTotalBrute, BigDecimal montantReglementCouvert, BigDecimal montantPayer, String picture, Timestamp whenDone, String whoDone, Boolean onDeleted, String direction, String division, String service, String telephone) {
        super(VAdherent.V_ADHERENT);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, sexe);
        set(4, matricule);
        set(5, codeCarnet);
        set(6, categorie);
        set(7, fonction);
        set(8, structureSigle);
        set(9, dateNaiss);
        set(10, age);
        set(11, datePriseService);
        set(12, anciennete);
        set(13, salaireNet);
        set(14, pourcentageTotalRetenue);
        set(15, totalCotisationAgent);
        set(16, totalCreditAnnuelle);
        set(17, totalCreditAConsomer);
        set(18, montantTotalBrute);
        set(19, montantReglementCouvert);
        set(20, montantPayer);
        set(21, picture);
        set(22, whenDone);
        set(23, whoDone);
        set(24, onDeleted);
        set(25, direction);
        set(26, division);
        set(27, service);
        set(28, telephone);
    }
}
