/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VBonDeCommande;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VBonDeCommandeRecord extends TableRecordImpl<VBonDeCommandeRecord> {

    private static final long serialVersionUID = 324855596;

    /**
     * Setter for <code>public.v_bon_de_commande.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.code_carnet</code>.
     */
    public void setCodeCarnet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.code_carnet</code>.
     */
    public String getCodeCarnet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.id_adherent</code>.
     */
    public void setIdAdherent(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.id_adherent</code>.
     */
    public Long getIdAdherent() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.matricule</code>.
     */
    public void setMatricule(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.structure</code>.
     */
    public void setStructure(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.structure</code>.
     */
    public String getStructure() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.annee</code>.
     */
    public void setAnnee(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.annee</code>.
     */
    public String getAnnee() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.prestation</code>.
     */
    public void setPrestation(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.couverture</code>.
     */
    public void setCouverture(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.nom_ay</code>.
     */
    public void setNomAy(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.nom_ay</code>.
     */
    public String getNomAy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.lien</code>.
     */
    public void setLien(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.lien</code>.
     */
    public String getLien() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.genre</code>.
     */
    public void setGenre(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.genre</code>.
     */
    public String getGenre() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.ayant_droit</code>.
     */
    public void setAyantDroit(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.ayant_droit</code>.
     */
    public Long getAyantDroit() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.montant_total</code>.
     */
    public void setMontantTotal(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.montant_total</code>.
     */
    public Long getMontantTotal() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.montant_reglement</code>.
     */
    public void setMontantReglement(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.montant_reglement</code>.
     */
    public Long getMontantReglement() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.montant_paye</code>.
     */
    public void setMontantPaye(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.montant_paye</code>.
     */
    public Long getMontantPaye() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>public.v_bon_de_commande.id_structure</code>.
     */
    public void setIdStructure(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_bon_de_commande.id_structure</code>.
     */
    public Long getIdStructure() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VBonDeCommandeRecord
     */
    public VBonDeCommandeRecord() {
        super(VBonDeCommande.V_BON_DE_COMMANDE);
    }

    /**
     * Create a detached, initialised VBonDeCommandeRecord
     */
    public VBonDeCommandeRecord(Long id, String nomAd, String prenomAd, String codeCarnet, Long idAdherent, String matricule, String refFacture, String structure, Timestamp datePayement, String whoDone, Timestamp whenDone, String annee, Boolean onDeleted, String prestation, String couverture, String nomAy, String lien, String genre, Long ayantDroit, Long montantTotal, Long montantReglement, Long montantPaye, Long idStructure) {
        super(VBonDeCommande.V_BON_DE_COMMANDE);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, codeCarnet);
        set(4, idAdherent);
        set(5, matricule);
        set(6, refFacture);
        set(7, structure);
        set(8, datePayement);
        set(9, whoDone);
        set(10, whenDone);
        set(11, annee);
        set(12, onDeleted);
        set(13, prestation);
        set(14, couverture);
        set(15, nomAy);
        set(16, lien);
        set(17, genre);
        set(18, ayantDroit);
        set(19, montantTotal);
        set(20, montantReglement);
        set(21, montantPaye);
        set(22, idStructure);
    }
}
