/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VHopitaux;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VHopitauxRecord extends TableRecordImpl<VHopitauxRecord> implements Record10<Long, String, String, Timestamp, Boolean, String, String, String, Boolean, String> {

    private static final long serialVersionUID = -345742355;

    /**
     * Setter for <code>public.v_hopitaux.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_hopitaux.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_hopitaux.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_hopitaux.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.v_hopitaux.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.v_hopitaux.telephone</code>.
     */
    public void setTelephone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_hopitaux.statut_structure</code>.
     */
    public void setStatutStructure(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.statut_structure</code>.
     */
    public String getStatutStructure() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_hopitaux.type_structure</code>.
     */
    public void setTypeStructure(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.type_structure</code>.
     */
    public String getTypeStructure() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_hopitaux.suspension</code>.
     */
    public void setSuspension(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.suspension</code>.
     */
    public Boolean getSuspension() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.v_hopitaux.region</code>.
     */
    public void setRegion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_hopitaux.region</code>.
     */
    public String getRegion() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Timestamp, Boolean, String, String, String, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Timestamp, Boolean, String, String, String, Boolean, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VHopitaux.V_HOPITAUX.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VHopitaux.V_HOPITAUX.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VHopitaux.V_HOPITAUX.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return VHopitaux.V_HOPITAUX.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return VHopitaux.V_HOPITAUX.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VHopitaux.V_HOPITAUX.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VHopitaux.V_HOPITAUX.STATUT_STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VHopitaux.V_HOPITAUX.TYPE_STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return VHopitaux.V_HOPITAUX.SUSPENSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VHopitaux.V_HOPITAUX.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatutStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTypeStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getSuspension();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatutStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTypeStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getSuspension();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value3(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value4(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value6(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value7(String value) {
        setStatutStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value8(String value) {
        setTypeStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value9(Boolean value) {
        setSuspension(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord value10(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitauxRecord values(Long value1, String value2, String value3, Timestamp value4, Boolean value5, String value6, String value7, String value8, Boolean value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VHopitauxRecord
     */
    public VHopitauxRecord() {
        super(VHopitaux.V_HOPITAUX);
    }

    /**
     * Create a detached, initialised VHopitauxRecord
     */
    public VHopitauxRecord(Long id, String libelle, String whoDone, Timestamp whenDone, Boolean isDeleted, String telephone, String statutStructure, String typeStructure, Boolean suspension, String region) {
        super(VHopitaux.V_HOPITAUX);

        set(0, id);
        set(1, libelle);
        set(2, whoDone);
        set(3, whenDone);
        set(4, isDeleted);
        set(5, telephone);
        set(6, statutStructure);
        set(7, typeStructure);
        set(8, suspension);
        set(9, region);
    }
}
