/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.VNbrBonExpirer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonExpirerRecord extends TableRecordImpl<VNbrBonExpirerRecord> implements Record1<Long> {

    private static final long serialVersionUID = 852136567;

    /**
     * Setter for <code>public.v_nbr_bon_expirer.count</code>.
     */
    public void setCount(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_nbr_bon_expirer.count</code>.
     */
    public Long getCount() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VNbrBonExpirer.V_NBR_BON_EXPIRER.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonExpirerRecord value1(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonExpirerRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VNbrBonExpirerRecord
     */
    public VNbrBonExpirerRecord() {
        super(VNbrBonExpirer.V_NBR_BON_EXPIRER);
    }

    /**
     * Create a detached, initialised VNbrBonExpirerRecord
     */
    public VNbrBonExpirerRecord(Long count) {
        super(VNbrBonExpirer.V_NBR_BON_EXPIRER);

        set(0, count);
    }
}
