/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import javax.annotation.Generated;

import models.tables.VNbrBonEnInstance;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonEnInstanceRecord extends TableRecordImpl<VNbrBonEnInstanceRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1309685151;

    /**
     * Setter for <code>public.v_nbr_bon_en_instance.count</code>.
     */
    public void setCount(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_nbr_bon_en_instance.count</code>.
     */
    public Long getCount() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VNbrBonEnInstance.V_NBR_BON_EN_INSTANCE.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonEnInstanceRecord value1(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonEnInstanceRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VNbrBonEnInstanceRecord
     */
    public VNbrBonEnInstanceRecord() {
        super(VNbrBonEnInstance.V_NBR_BON_EN_INSTANCE);
    }

    /**
     * Create a detached, initialised VNbrBonEnInstanceRecord
     */
    public VNbrBonEnInstanceRecord(Long count) {
        super(VNbrBonEnInstance.V_NBR_BON_EN_INSTANCE);

        set(0, count);
    }
}
