/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VReglementDetails;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementDetailsRecord extends TableRecordImpl<VReglementDetailsRecord> {

    private static final long serialVersionUID = -425737594;

    /**
     * Setter for <code>public.v_reglement_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_reglement_details.reglement</code>.
     */
    public void setReglement(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.reglement</code>.
     */
    public Long getReglement() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.v_reglement_details.intitule</code>.
     */
    public void setIntitule(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.intitule</code>.
     */
    public String getIntitule() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_reglement_details.montant</code>.
     */
    public void setMontant(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.montant</code>.
     */
    public Long getMontant() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.v_reglement_details.quantite</code>.
     */
    public void setQuantite(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.quantite</code>.
     */
    public Long getQuantite() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.v_reglement_details.prix_unitaire</code>.
     */
    public void setPrixUnitaire(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prix_unitaire</code>.
     */
    public Long getPrixUnitaire() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.v_reglement_details.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_reglement_details.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.v_reglement_details.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.v_reglement_details.last_update</code>.
     */
    public void setLastUpdate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.last_update</code>.
     */
    public Timestamp getLastUpdate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.v_reglement_details.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_reglement_details.id_bon</code>.
     */
    public void setIdBon(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.id_bon</code>.
     */
    public Long getIdBon() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.v_reglement_details.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_reglement_details.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_reglement_details.matricule</code>.
     */
    public void setMatricule(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_reglement_details.structure</code>.
     */
    public void setStructure(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.structure</code>.
     */
    public String getStructure() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_reglement_details.couverture</code>.
     */
    public void setCouverture(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_reglement_details.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>public.v_reglement_details.prestation</code>.
     */
    public void setPrestation(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_reglement_details.lien</code>.
     */
    public void setLien(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.lien</code>.
     */
    public String getLien() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.v_reglement_details.is_confirmed_bon</code>.
     */
    public void setIsConfirmedBon(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.is_confirmed_bon</code>.
     */
    public Boolean getIsConfirmedBon() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>public.v_reglement_details.when_confirmed_bon</code>.
     */
    public void setWhenConfirmedBon(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.when_confirmed_bon</code>.
     */
    public Timestamp getWhenConfirmedBon() {
        return (Timestamp) get(21);
    }

    /**
     * Setter for <code>public.v_reglement_details.date_expiration</code>.
     */
    public void setDateExpiration(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.date_expiration</code>.
     */
    public Timestamp getDateExpiration() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>public.v_reglement_details.total_couvert</code>.
     */
    public void setTotalCouvert(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.total_couvert</code>.
     */
    public Long getTotalCouvert() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>public.v_reglement_details.total_restant</code>.
     */
    public void setTotalRestant(Long value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.total_restant</code>.
     */
    public Long getTotalRestant() {
        return (Long) get(24);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VReglementDetailsRecord
     */
    public VReglementDetailsRecord() {
        super(VReglementDetails.V_REGLEMENT_DETAILS);
    }

    /**
     * Create a detached, initialised VReglementDetailsRecord
     */
    public VReglementDetailsRecord(Long id, Long reglement, String intitule, Long montant, Long quantite, Long prixUnitaire, String whoDone, Timestamp whenDone, Boolean onDeleted, Timestamp lastUpdate, String refFacture, Long idBon, String nomAd, String prenomAd, String matricule, String structure, String couverture, Timestamp datePayement, String prestation, String lien, Boolean isConfirmedBon, Timestamp whenConfirmedBon, Timestamp dateExpiration, Long totalCouvert, Long totalRestant) {
        super(VReglementDetails.V_REGLEMENT_DETAILS);

        set(0, id);
        set(1, reglement);
        set(2, intitule);
        set(3, montant);
        set(4, quantite);
        set(5, prixUnitaire);
        set(6, whoDone);
        set(7, whenDone);
        set(8, onDeleted);
        set(9, lastUpdate);
        set(10, refFacture);
        set(11, idBon);
        set(12, nomAd);
        set(13, prenomAd);
        set(14, matricule);
        set(15, structure);
        set(16, couverture);
        set(17, datePayement);
        set(18, prestation);
        set(19, lien);
        set(20, isConfirmedBon);
        set(21, whenConfirmedBon);
        set(22, dateExpiration);
        set(23, totalCouvert);
        set(24, totalRestant);
    }
}
