/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VReglementDetails;

import org.jooq.Field;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementDetailsRecord extends TableRecordImpl<VReglementDetailsRecord> implements Record22<Long, Long, String, Long, Long, Long, String, Timestamp, Boolean, Timestamp, String, Long, String, String, String, String, String, Timestamp, String, String, Long, Long> {

    private static final long serialVersionUID = -281228249;

    /**
     * Setter for <code>public.v_reglement_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_reglement_details.reglement</code>.
     */
    public void setReglement(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.reglement</code>.
     */
    public Long getReglement() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.v_reglement_details.intitule</code>.
     */
    public void setIntitule(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.intitule</code>.
     */
    public String getIntitule() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_reglement_details.montant</code>.
     */
    public void setMontant(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.montant</code>.
     */
    public Long getMontant() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.v_reglement_details.quantite</code>.
     */
    public void setQuantite(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.quantite</code>.
     */
    public Long getQuantite() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.v_reglement_details.prix_unitaire</code>.
     */
    public void setPrixUnitaire(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prix_unitaire</code>.
     */
    public Long getPrixUnitaire() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.v_reglement_details.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_reglement_details.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.v_reglement_details.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.v_reglement_details.last_update</code>.
     */
    public void setLastUpdate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.last_update</code>.
     */
    public Timestamp getLastUpdate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.v_reglement_details.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_reglement_details.id_bon</code>.
     */
    public void setIdBon(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.id_bon</code>.
     */
    public Long getIdBon() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.v_reglement_details.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_reglement_details.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_reglement_details.matricule</code>.
     */
    public void setMatricule(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_reglement_details.structure</code>.
     */
    public void setStructure(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.structure</code>.
     */
    public String getStructure() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.v_reglement_details.couverture</code>.
     */
    public void setCouverture(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_reglement_details.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>public.v_reglement_details.prestation</code>.
     */
    public void setPrestation(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_reglement_details.lien</code>.
     */
    public void setLien(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.lien</code>.
     */
    public String getLien() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.v_reglement_details.total_couvert</code>.
     */
    public void setTotalCouvert(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.total_couvert</code>.
     */
    public Long getTotalCouvert() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.v_reglement_details.total_restant</code>.
     */
    public void setTotalRestant(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_reglement_details.total_restant</code>.
     */
    public Long getTotalRestant() {
        return (Long) get(21);
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Long, String, Long, Long, Long, String, Timestamp, Boolean, Timestamp, String, Long, String, String, String, String, String, Timestamp, String, String, Long, Long> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Long, String, Long, Long, Long, String, Timestamp, Boolean, Timestamp, String, Long, String, String, String, String, String, Timestamp, String, String, Long, Long> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VReglementDetails.V_REGLEMENT_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return VReglementDetails.V_REGLEMENT_DETAILS.REGLEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VReglementDetails.V_REGLEMENT_DETAILS.INTITULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return VReglementDetails.V_REGLEMENT_DETAILS.MONTANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return VReglementDetails.V_REGLEMENT_DETAILS.QUANTITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return VReglementDetails.V_REGLEMENT_DETAILS.PRIX_UNITAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VReglementDetails.V_REGLEMENT_DETAILS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VReglementDetails.V_REGLEMENT_DETAILS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return VReglementDetails.V_REGLEMENT_DETAILS.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return VReglementDetails.V_REGLEMENT_DETAILS.LAST_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VReglementDetails.V_REGLEMENT_DETAILS.REF_FACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return VReglementDetails.V_REGLEMENT_DETAILS.ID_BON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VReglementDetails.V_REGLEMENT_DETAILS.NOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return VReglementDetails.V_REGLEMENT_DETAILS.PRENOM_AD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VReglementDetails.V_REGLEMENT_DETAILS.MATRICULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return VReglementDetails.V_REGLEMENT_DETAILS.STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return VReglementDetails.V_REGLEMENT_DETAILS.COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return VReglementDetails.V_REGLEMENT_DETAILS.DATE_PAYEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return VReglementDetails.V_REGLEMENT_DETAILS.PRESTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return VReglementDetails.V_REGLEMENT_DETAILS.LIEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field21() {
        return VReglementDetails.V_REGLEMENT_DETAILS.TOTAL_COUVERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field22() {
        return VReglementDetails.V_REGLEMENT_DETAILS.TOTAL_RESTANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getReglement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getPrixUnitaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getIdBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getLien();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component21() {
        return getTotalCouvert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component22() {
        return getTotalRestant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getReglement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getPrixUnitaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getIdBon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getNomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getPrenomAd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getDatePayement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getLien();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value21() {
        return getTotalCouvert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value22() {
        return getTotalRestant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value2(Long value) {
        setReglement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value3(String value) {
        setIntitule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value4(Long value) {
        setMontant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value5(Long value) {
        setQuantite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value6(Long value) {
        setPrixUnitaire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value7(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value8(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value9(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value10(Timestamp value) {
        setLastUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value11(String value) {
        setRefFacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value12(Long value) {
        setIdBon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value13(String value) {
        setNomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value14(String value) {
        setPrenomAd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value15(String value) {
        setMatricule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value16(String value) {
        setStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value17(String value) {
        setCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value18(Timestamp value) {
        setDatePayement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value19(String value) {
        setPrestation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value20(String value) {
        setLien(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value21(Long value) {
        setTotalCouvert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord value22(Long value) {
        setTotalRestant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetailsRecord values(Long value1, Long value2, String value3, Long value4, Long value5, Long value6, String value7, Timestamp value8, Boolean value9, Timestamp value10, String value11, Long value12, String value13, String value14, String value15, String value16, String value17, Timestamp value18, String value19, String value20, Long value21, Long value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VReglementDetailsRecord
     */
    public VReglementDetailsRecord() {
        super(VReglementDetails.V_REGLEMENT_DETAILS);
    }

    /**
     * Create a detached, initialised VReglementDetailsRecord
     */
    public VReglementDetailsRecord(Long id, Long reglement, String intitule, Long montant, Long quantite, Long prixUnitaire, String whoDone, Timestamp whenDone, Boolean onDeleted, Timestamp lastUpdate, String refFacture, Long idBon, String nomAd, String prenomAd, String matricule, String structure, String couverture, Timestamp datePayement, String prestation, String lien, Long totalCouvert, Long totalRestant) {
        super(VReglementDetails.V_REGLEMENT_DETAILS);

        set(0, id);
        set(1, reglement);
        set(2, intitule);
        set(3, montant);
        set(4, quantite);
        set(5, prixUnitaire);
        set(6, whoDone);
        set(7, whenDone);
        set(8, onDeleted);
        set(9, lastUpdate);
        set(10, refFacture);
        set(11, idBon);
        set(12, nomAd);
        set(13, prenomAd);
        set(14, matricule);
        set(15, structure);
        set(16, couverture);
        set(17, datePayement);
        set(18, prestation);
        set(19, lien);
        set(20, totalCouvert);
        set(21, totalRestant);
    }
}
