/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.tables.VRegPriseEnCharge;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VRegPriseEnChargeRecord extends TableRecordImpl<VRegPriseEnChargeRecord> {

    private static final long serialVersionUID = 57275507;

    /**
     * Setter for <code>public.v_reg_prise_en_charge.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.nom_ad</code>.
     */
    public void setNomAd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.nom_ad</code>.
     */
    public String getNomAd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.prenom_ad</code>.
     */
    public void setPrenomAd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.prenom_ad</code>.
     */
    public String getPrenomAd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.id_adherent</code>.
     */
    public void setIdAdherent(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.id_adherent</code>.
     */
    public Long getIdAdherent() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.matricule</code>.
     */
    public void setMatricule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.matricule</code>.
     */
    public String getMatricule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.structure</code>.
     */
    public void setStructure(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.structure</code>.
     */
    public String getStructure() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.date_payement</code>.
     */
    public void setDatePayement(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.date_payement</code>.
     */
    public Timestamp getDatePayement() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.is_confirmed_bon</code>.
     */
    public void setIsConfirmedBon(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.is_confirmed_bon</code>.
     */
    public Boolean getIsConfirmedBon() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.when_confirmed_bon</code>.
     */
    public void setWhenConfirmedBon(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.when_confirmed_bon</code>.
     */
    public Timestamp getWhenConfirmedBon() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.date_expiration</code>.
     */
    public void setDateExpiration(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.date_expiration</code>.
     */
    public Timestamp getDateExpiration() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.type_reglement</code>.
     */
    public void setTypeReglement(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.type_reglement</code>.
     */
    public String getTypeReglement() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.annee</code>.
     */
    public void setAnnee(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.annee</code>.
     */
    public String getAnnee() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.prestation</code>.
     */
    public void setPrestation(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.prestation</code>.
     */
    public String getPrestation() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.couverture</code>.
     */
    public void setCouverture(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.couverture</code>.
     */
    public String getCouverture() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.taux_public</code>.
     */
    public void setTauxPublic(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.taux_public</code>.
     */
    public String getTauxPublic() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.taux_prive</code>.
     */
    public void setTauxPrive(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.taux_prive</code>.
     */
    public String getTauxPrive() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.type_structure</code>.
     */
    public void setTypeStructure(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.type_structure</code>.
     */
    public String getTypeStructure() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.statut_structure</code>.
     */
    public void setStatutStructure(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.statut_structure</code>.
     */
    public String getStatutStructure() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.nom_ay</code>.
     */
    public void setNomAy(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.nom_ay</code>.
     */
    public String getNomAy() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.lien</code>.
     */
    public void setLien(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.lien</code>.
     */
    public String getLien() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.genre</code>.
     */
    public void setGenre(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.genre</code>.
     */
    public String getGenre() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.ayant_droit</code>.
     */
    public void setAyantDroit(Long value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.ayant_droit</code>.
     */
    public Long getAyantDroit() {
        return (Long) get(25);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.montant_total</code>.
     */
    public void setMontantTotal(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.montant_total</code>.
     */
    public Long getMontantTotal() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.taux_couverture_effectif</code>.
     */
    public void setTauxCouvertureEffectif(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.taux_couverture_effectif</code>.
     */
    public String getTauxCouvertureEffectif() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.montant_reglement</code>.
     */
    public void setMontantReglement(Long value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.montant_reglement</code>.
     */
    public Long getMontantReglement() {
        return (Long) get(28);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.montant_paye</code>.
     */
    public void setMontantPaye(Long value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.montant_paye</code>.
     */
    public Long getMontantPaye() {
        return (Long) get(29);
    }

    /**
     * Setter for <code>public.v_reg_prise_en_charge.id_structure</code>.
     */
    public void setIdStructure(Long value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.v_reg_prise_en_charge.id_structure</code>.
     */
    public Long getIdStructure() {
        return (Long) get(30);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VRegPriseEnChargeRecord
     */
    public VRegPriseEnChargeRecord() {
        super(VRegPriseEnCharge.V_REG_PRISE_EN_CHARGE);
    }

    /**
     * Create a detached, initialised VRegPriseEnChargeRecord
     */
    public VRegPriseEnChargeRecord(Long id, String nomAd, String prenomAd, Long idAdherent, String matricule, String refFacture, String structure, Timestamp datePayement, String whoDone, Timestamp whenDone, Boolean isConfirmedBon, Timestamp whenConfirmedBon, Timestamp dateExpiration, String typeReglement, String annee, Boolean onDeleted, String prestation, String couverture, String tauxPublic, String tauxPrive, String typeStructure, String statutStructure, String nomAy, String lien, String genre, Long ayantDroit, Long montantTotal, String tauxCouvertureEffectif, Long montantReglement, Long montantPaye, Long idStructure) {
        super(VRegPriseEnCharge.V_REG_PRISE_EN_CHARGE);

        set(0, id);
        set(1, nomAd);
        set(2, prenomAd);
        set(3, idAdherent);
        set(4, matricule);
        set(5, refFacture);
        set(6, structure);
        set(7, datePayement);
        set(8, whoDone);
        set(9, whenDone);
        set(10, isConfirmedBon);
        set(11, whenConfirmedBon);
        set(12, dateExpiration);
        set(13, typeReglement);
        set(14, annee);
        set(15, onDeleted);
        set(16, prestation);
        set(17, couverture);
        set(18, tauxPublic);
        set(19, tauxPrive);
        set(20, typeStructure);
        set(21, statutStructure);
        set(22, nomAy);
        set(23, lien);
        set(24, genre);
        set(25, ayantDroit);
        set(26, montantTotal);
        set(27, tauxCouvertureEffectif);
        set(28, montantReglement);
        set(29, montantPaye);
        set(30, idStructure);
    }
}
