/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.EtudeConsommationsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Table stockant les données d'étude de consommations des bons de commande
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudeConsommations extends TableImpl<EtudeConsommationsRecord> {

    private static final long serialVersionUID = -48014477;

    /**
     * The reference instance of <code>public.etude_consommations</code>
     */
    public static final EtudeConsommations ETUDE_CONSOMMATIONS = new EtudeConsommations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EtudeConsommationsRecord> getRecordType() {
        return EtudeConsommationsRecord.class;
    }

    /**
     * The column <code>public.etude_consommations.id</code>.
     */
    public final TableField<EtudeConsommationsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('etude_consommations_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.etude_consommations.numero_carnet</code>. Numéro du carnet de l'adhérent
     */
    public final TableField<EtudeConsommationsRecord, String> NUMERO_CARNET = createField("numero_carnet", org.jooq.impl.SQLDataType.VARCHAR(50), this, "Numéro du carnet de l'adhérent");

    /**
     * The column <code>public.etude_consommations.code_agent</code>. Code unique de l'agent
     */
    public final TableField<EtudeConsommationsRecord, String> CODE_AGENT = createField("code_agent", org.jooq.impl.SQLDataType.VARCHAR(50), this, "Code unique de l'agent");

    /**
     * The column <code>public.etude_consommations.nom_prenoms</code>.
     */
    public final TableField<EtudeConsommationsRecord, String> NOM_PRENOMS = createField("nom_prenoms", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.etude_consommations.agent</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> AGENT = createField("agent", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>public.etude_consommations.conjoint</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> CONJOINT = createField("conjoint", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>public.etude_consommations.enfants</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> ENFANTS = createField("enfants", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>public.etude_consommations.pere</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> PERE = createField("pere", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>public.etude_consommations.mere</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> MERE = createField("mere", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>public.etude_consommations.salaire_base</code>. Salaire de base de l'agent
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> SALAIRE_BASE = createField("salaire_base", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "Salaire de base de l'agent");

    /**
     * The column <code>public.etude_consommations.pourcentage_retenir</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> POURCENTAGE_RETENIR = createField("pourcentage_retenir", org.jooq.impl.SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.etude_consommations.retenue_mensuelle</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> RETENUE_MENSUELLE = createField("retenue_mensuelle", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.credit_annuel</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> CREDIT_ANNUEL = createField("credit_annuel", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.credit_annuel_x2</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> CREDIT_ANNUEL_X2 = createField("credit_annuel_x2", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.consommation_bons</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> CONSOMMATION_BONS = createField("consommation_bons", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.consommation_pc</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> CONSOMMATION_PC = createField("consommation_pc", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.remboursement</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> REMBOURSEMENT = createField("remboursement", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.total_consommation</code>. Total des consommations (Bons + PC + Remboursement)
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> TOTAL_CONSOMMATION = createField("total_consommation", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "Total des consommations (Bons + PC + Remboursement)");

    /**
     * The column <code>public.etude_consommations.solde_1</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> SOLDE_1 = createField("solde_1", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.solde_2</code>.
     */
    public final TableField<EtudeConsommationsRecord, BigDecimal> SOLDE_2 = createField("solde_2", org.jooq.impl.SQLDataType.NUMERIC(15, 2), this, "");

    /**
     * The column <code>public.etude_consommations.statut_avertissement</code>. Statut d'avertissement (AVERTIS, etc.)
     */
    public final TableField<EtudeConsommationsRecord, String> STATUT_AVERTISSEMENT = createField("statut_avertissement", org.jooq.impl.SQLDataType.VARCHAR(50), this, "Statut d'avertissement (AVERTIS, etc.)");

    /**
     * The column <code>public.etude_consommations.statut_suspension</code>. Statut de suspension (SUSPENDUS, etc.)
     */
    public final TableField<EtudeConsommationsRecord, String> STATUT_SUSPENSION = createField("statut_suspension", org.jooq.impl.SQLDataType.VARCHAR(50), this, "Statut de suspension (SUSPENDUS, etc.)");

    /**
     * The column <code>public.etude_consommations.fichier_source</code>.
     */
    public final TableField<EtudeConsommationsRecord, String> FICHIER_SOURCE = createField("fichier_source", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.etude_consommations.date_import</code>.
     */
    public final TableField<EtudeConsommationsRecord, Timestamp> DATE_IMPORT = createField("date_import", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.etude_consommations.utilisateur_import</code>.
     */
    public final TableField<EtudeConsommationsRecord, String> UTILISATEUR_IMPORT = createField("utilisateur_import", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>public.etude_consommations</code> table reference
     */
    public EtudeConsommations() {
        this(DSL.name("etude_consommations"), null);
    }

    /**
     * Create an aliased <code>public.etude_consommations</code> table reference
     */
    public EtudeConsommations(String alias) {
        this(DSL.name(alias), ETUDE_CONSOMMATIONS);
    }

    /**
     * Create an aliased <code>public.etude_consommations</code> table reference
     */
    public EtudeConsommations(Name alias) {
        this(alias, ETUDE_CONSOMMATIONS);
    }

    private EtudeConsommations(Name alias, Table<EtudeConsommationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private EtudeConsommations(Name alias, Table<EtudeConsommationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Table stockant les données d'étude de consommations des bons de commande");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ETUDE_CONSOMMATIONS_PKEY, Indexes.IDX_DATE_IMPORT, Indexes.IDX_NOM_PRENOMS, Indexes.IDX_NUMERO_CARNET, Indexes.IDX_STATUT_AVERTISSEMENT, Indexes.IDX_STATUT_SUSPENSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EtudeConsommationsRecord, Long> getIdentity() {
        return Keys.IDENTITY_ETUDE_CONSOMMATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EtudeConsommationsRecord> getPrimaryKey() {
        return Keys.ETUDE_CONSOMMATIONS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EtudeConsommationsRecord>> getKeys() {
        return Arrays.<UniqueKey<EtudeConsommationsRecord>>asList(Keys.ETUDE_CONSOMMATIONS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudeConsommations as(String alias) {
        return new EtudeConsommations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudeConsommations as(Name alias) {
        return new EtudeConsommations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EtudeConsommations rename(String name) {
        return new EtudeConsommations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EtudeConsommations rename(Name name) {
        return new EtudeConsommations(name, null);
    }
}
