/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.Indexes;
import models.Keys;
import models.Public;
import models.tables.records.OtpMessageRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtpMessage extends TableImpl<OtpMessageRecord> {

    private static final long serialVersionUID = -10655713;

    /**
     * The reference instance of <code>public.otp_message</code>
     */
    public static final OtpMessage OTP_MESSAGE = new OtpMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OtpMessageRecord> getRecordType() {
        return OtpMessageRecord.class;
    }

    /**
     * The column <code>public.otp_message.id</code>.
     */
    public final TableField<OtpMessageRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('otp_message_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.otp_message.phone</code>.
     */
    public final TableField<OtpMessageRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.otp_message.code</code>.
     */
    public final TableField<OtpMessageRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.otp_message.message_texte</code>.
     */
    public final TableField<OtpMessageRecord, String> MESSAGE_TEXTE = createField("message_texte", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.otp_message.bon_commande</code>.
     */
    public final TableField<OtpMessageRecord, Long> BON_COMMANDE = createField("bon_commande", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.otp_message.created_at</code>.
     */
    public final TableField<OtpMessageRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.otp_message.expires_at</code>.
     */
    public final TableField<OtpMessageRecord, Timestamp> EXPIRES_AT = createField("expires_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.otp_message.is_used</code>.
     */
    public final TableField<OtpMessageRecord, Boolean> IS_USED = createField("is_used", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.otp_message.is_sent</code>.
     */
    public final TableField<OtpMessageRecord, Boolean> IS_SENT = createField("is_sent", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.otp_message.sent_response</code>.
     */
    public final TableField<OtpMessageRecord, String> SENT_RESPONSE = createField("sent_response", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.otp_message.attempt_count</code>.
     */
    public final TableField<OtpMessageRecord, Integer> ATTEMPT_COUNT = createField("attempt_count", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.otp_message.context</code>.
     */
    public final TableField<OtpMessageRecord, String> CONTEXT = createField("context", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>public.otp_message</code> table reference
     */
    public OtpMessage() {
        this(DSL.name("otp_message"), null);
    }

    /**
     * Create an aliased <code>public.otp_message</code> table reference
     */
    public OtpMessage(String alias) {
        this(DSL.name(alias), OTP_MESSAGE);
    }

    /**
     * Create an aliased <code>public.otp_message</code> table reference
     */
    public OtpMessage(Name alias) {
        this(alias, OTP_MESSAGE);
    }

    private OtpMessage(Name alias, Table<OtpMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private OtpMessage(Name alias, Table<OtpMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OTP_MESSAGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OtpMessageRecord, Long> getIdentity() {
        return Keys.IDENTITY_OTP_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OtpMessageRecord> getPrimaryKey() {
        return Keys.OTP_MESSAGE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OtpMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<OtpMessageRecord>>asList(Keys.OTP_MESSAGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessage as(String alias) {
        return new OtpMessage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OtpMessage as(Name alias) {
        return new OtpMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OtpMessage rename(String name) {
        return new OtpMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtpMessage rename(Name name) {
        return new OtpMessage(name, null);
    }
}
