/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VAdherentBadgesRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAdherentBadges extends TableImpl<VAdherentBadgesRecord> {

    private static final long serialVersionUID = 1011082502;

    /**
     * The reference instance of <code>public.v_adherent_badges</code>
     */
    public static final VAdherentBadges V_ADHERENT_BADGES = new VAdherentBadges();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VAdherentBadgesRecord> getRecordType() {
        return VAdherentBadgesRecord.class;
    }

    /**
     * The column <code>public.v_adherent_badges.id</code>.
     */
    public final TableField<VAdherentBadgesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_adherent_badges.nom_ad</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.prenom_ad</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.sexe</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> SEXE = createField("sexe", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.matricule</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.categorie</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_adherent_badges.fonction</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> FONCTION = createField("fonction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.structure_sigle</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> STRUCTURE_SIGLE = createField("structure_sigle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.date_naiss</code>.
     */
    public final TableField<VAdherentBadgesRecord, Timestamp> DATE_NAISS = createField("date_naiss", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_badges.age</code>.
     */
    public final TableField<VAdherentBadgesRecord, Double> AGE = createField("age", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent_badges.date_prise_service</code>.
     */
    public final TableField<VAdherentBadgesRecord, Timestamp> DATE_PRISE_SERVICE = createField("date_prise_service", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_badges.anciennete</code>.
     */
    public final TableField<VAdherentBadgesRecord, Double> ANCIENNETE = createField("anciennete", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_adherent_badges.picture</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.when_done</code>.
     */
    public final TableField<VAdherentBadgesRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_adherent_badges.who_done</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.on_deleted</code>.
     */
    public final TableField<VAdherentBadgesRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_adherent_badges.is_ok_for_printing</code>.
     */
    public final TableField<VAdherentBadgesRecord, Boolean> IS_OK_FOR_PRINTING = createField("is_ok_for_printing", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_adherent_badges.is_member</code>.
     */
    public final TableField<VAdherentBadgesRecord, Boolean> IS_MEMBER = createField("is_member", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_adherent_badges.direction</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.division</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> DIVISION = createField("division", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.service</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> SERVICE = createField("service", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_adherent_badges.telephone</code>.
     */
    public final TableField<VAdherentBadgesRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_adherent_badges</code> table reference
     */
    public VAdherentBadges() {
        this(DSL.name("v_adherent_badges"), null);
    }

    /**
     * Create an aliased <code>public.v_adherent_badges</code> table reference
     */
    public VAdherentBadges(String alias) {
        this(DSL.name(alias), V_ADHERENT_BADGES);
    }

    /**
     * Create an aliased <code>public.v_adherent_badges</code> table reference
     */
    public VAdherentBadges(Name alias) {
        this(alias, V_ADHERENT_BADGES);
    }

    private VAdherentBadges(Name alias, Table<VAdherentBadgesRecord> aliased) {
        this(alias, aliased, null);
    }

    private VAdherentBadges(Name alias, Table<VAdherentBadgesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadges as(String alias) {
        return new VAdherentBadges(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAdherentBadges as(Name alias) {
        return new VAdherentBadges(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherentBadges rename(String name) {
        return new VAdherentBadges(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VAdherentBadges rename(Name name) {
        return new VAdherentBadges(name, null);
    }
}
