/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VBonDeCommandeRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VBonDeCommande extends TableImpl<VBonDeCommandeRecord> {

    private static final long serialVersionUID = -639264666;

    /**
     * The reference instance of <code>public.v_bon_de_commande</code>
     */
    public static final VBonDeCommande V_BON_DE_COMMANDE = new VBonDeCommande();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VBonDeCommandeRecord> getRecordType() {
        return VBonDeCommandeRecord.class;
    }

    /**
     * The column <code>public.v_bon_de_commande.id</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.nom_ad</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.prenom_ad</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.id_adherent</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.matricule</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.code_carnet</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> CODE_CARNET = createField("code_carnet", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.ref_facture</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.structure</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.date_payement</code>.
     */
    public final TableField<VBonDeCommandeRecord, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_bon_de_commande.who_done</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.when_done</code>.
     */
    public final TableField<VBonDeCommandeRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_bon_de_commande.is_confirmed_bon</code>.
     */
    public final TableField<VBonDeCommandeRecord, Boolean> IS_CONFIRMED_BON = createField("is_confirmed_bon", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_bon_de_commande.when_confirmed_bon</code>.
     */
    public final TableField<VBonDeCommandeRecord, Timestamp> WHEN_CONFIRMED_BON = createField("when_confirmed_bon", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_bon_de_commande.date_expiration</code>.
     */
    public final TableField<VBonDeCommandeRecord, Timestamp> DATE_EXPIRATION = createField("date_expiration", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_bon_de_commande.type_reglement</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> TYPE_REGLEMENT = createField("type_reglement", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.annee</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.on_deleted</code>.
     */
    public final TableField<VBonDeCommandeRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_bon_de_commande.prestation</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_bon_de_commande.taux_effectif</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> TAUX_EFFECTIF = createField("taux_effectif", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.type_structure</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.statut_structure</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.nom_ay</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.lien</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.genre</code>.
     */
    public final TableField<VBonDeCommandeRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_bon_de_commande.ayant_droit</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> AYANT_DROIT = createField("ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.montant_total</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> MONTANT_TOTAL = createField("montant_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.montant_reglement</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> MONTANT_REGLEMENT = createField("montant_reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.montant_paye</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> MONTANT_PAYE = createField("montant_paye", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_bon_de_commande.id_structure</code>.
     */
    public final TableField<VBonDeCommandeRecord, Long> ID_STRUCTURE = createField("id_structure", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_bon_de_commande</code> table reference
     */
    public VBonDeCommande() {
        this(DSL.name("v_bon_de_commande"), null);
    }

    /**
     * Create an aliased <code>public.v_bon_de_commande</code> table reference
     */
    public VBonDeCommande(String alias) {
        this(DSL.name(alias), V_BON_DE_COMMANDE);
    }

    /**
     * Create an aliased <code>public.v_bon_de_commande</code> table reference
     */
    public VBonDeCommande(Name alias) {
        this(alias, V_BON_DE_COMMANDE);
    }

    private VBonDeCommande(Name alias, Table<VBonDeCommandeRecord> aliased) {
        this(alias, aliased, null);
    }

    private VBonDeCommande(Name alias, Table<VBonDeCommandeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBonDeCommande as(String alias) {
        return new VBonDeCommande(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBonDeCommande as(Name alias) {
        return new VBonDeCommande(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VBonDeCommande rename(String name) {
        return new VBonDeCommande(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VBonDeCommande rename(Name name) {
        return new VBonDeCommande(name, null);
    }
}
