/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VHopitauxRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VHopitaux extends TableImpl<VHopitauxRecord> {

    private static final long serialVersionUID = 879620081;

    /**
     * The reference instance of <code>public.v_hopitaux</code>
     */
    public static final VHopitaux V_HOPITAUX = new VHopitaux();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VHopitauxRecord> getRecordType() {
        return VHopitauxRecord.class;
    }

    /**
     * The column <code>public.v_hopitaux.id</code>.
     */
    public final TableField<VHopitauxRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_hopitaux.libelle</code>.
     */
    public final TableField<VHopitauxRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_hopitaux.who_done</code>.
     */
    public final TableField<VHopitauxRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_hopitaux.when_done</code>.
     */
    public final TableField<VHopitauxRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_hopitaux.is_deleted</code>.
     */
    public final TableField<VHopitauxRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_hopitaux.telephone</code>.
     */
    public final TableField<VHopitauxRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_hopitaux.statut_structure</code>.
     */
    public final TableField<VHopitauxRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_hopitaux.type_structure</code>.
     */
    public final TableField<VHopitauxRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_hopitaux.suspension</code>.
     */
    public final TableField<VHopitauxRecord, Boolean> SUSPENSION = createField("suspension", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_hopitaux.region</code>.
     */
    public final TableField<VHopitauxRecord, String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_hopitaux</code> table reference
     */
    public VHopitaux() {
        this(DSL.name("v_hopitaux"), null);
    }

    /**
     * Create an aliased <code>public.v_hopitaux</code> table reference
     */
    public VHopitaux(String alias) {
        this(DSL.name(alias), V_HOPITAUX);
    }

    /**
     * Create an aliased <code>public.v_hopitaux</code> table reference
     */
    public VHopitaux(Name alias) {
        this(alias, V_HOPITAUX);
    }

    private VHopitaux(Name alias, Table<VHopitauxRecord> aliased) {
        this(alias, aliased, null);
    }

    private VHopitaux(Name alias, Table<VHopitauxRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitaux as(String alias) {
        return new VHopitaux(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHopitaux as(Name alias) {
        return new VHopitaux(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VHopitaux rename(String name) {
        return new VHopitaux(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VHopitaux rename(Name name) {
        return new VHopitaux(name, null);
    }
}
