/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VNbrBonExpirerRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonExpirer extends TableImpl<VNbrBonExpirerRecord> {

    private static final long serialVersionUID = 992864542;

    /**
     * The reference instance of <code>public.v_nbr_bon_expirer</code>
     */
    public static final VNbrBonExpirer V_NBR_BON_EXPIRER = new VNbrBonExpirer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VNbrBonExpirerRecord> getRecordType() {
        return VNbrBonExpirerRecord.class;
    }

    /**
     * The column <code>public.v_nbr_bon_expirer.count</code>.
     */
    public final TableField<VNbrBonExpirerRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_nbr_bon_expirer</code> table reference
     */
    public VNbrBonExpirer() {
        this(DSL.name("v_nbr_bon_expirer"), null);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_expirer</code> table reference
     */
    public VNbrBonExpirer(String alias) {
        this(DSL.name(alias), V_NBR_BON_EXPIRER);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_expirer</code> table reference
     */
    public VNbrBonExpirer(Name alias) {
        this(alias, V_NBR_BON_EXPIRER);
    }

    private VNbrBonExpirer(Name alias, Table<VNbrBonExpirerRecord> aliased) {
        this(alias, aliased, null);
    }

    private VNbrBonExpirer(Name alias, Table<VNbrBonExpirerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonExpirer as(String alias) {
        return new VNbrBonExpirer(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonExpirer as(Name alias) {
        return new VNbrBonExpirer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonExpirer rename(String name) {
        return new VNbrBonExpirer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonExpirer rename(Name name) {
        return new VNbrBonExpirer(name, null);
    }
}
