/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VNbrBonValiderRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonValider extends TableImpl<VNbrBonValiderRecord> {

    private static final long serialVersionUID = -1986476518;

    /**
     * The reference instance of <code>public.v_nbr_bon_valider</code>
     */
    public static final VNbrBonValider V_NBR_BON_VALIDER = new VNbrBonValider();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VNbrBonValiderRecord> getRecordType() {
        return VNbrBonValiderRecord.class;
    }

    /**
     * The column <code>public.v_nbr_bon_valider.count</code>.
     */
    public final TableField<VNbrBonValiderRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_nbr_bon_valider</code> table reference
     */
    public VNbrBonValider() {
        this(DSL.name("v_nbr_bon_valider"), null);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_valider</code> table reference
     */
    public VNbrBonValider(String alias) {
        this(DSL.name(alias), V_NBR_BON_VALIDER);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_valider</code> table reference
     */
    public VNbrBonValider(Name alias) {
        this(alias, V_NBR_BON_VALIDER);
    }

    private VNbrBonValider(Name alias, Table<VNbrBonValiderRecord> aliased) {
        this(alias, aliased, null);
    }

    private VNbrBonValider(Name alias, Table<VNbrBonValiderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonValider as(String alias) {
        return new VNbrBonValider(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonValider as(Name alias) {
        return new VNbrBonValider(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonValider rename(String name) {
        return new VNbrBonValider(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonValider rename(Name name) {
        return new VNbrBonValider(name, null);
    }
}
