/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VNbrTotalBonRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrTotalBon extends TableImpl<VNbrTotalBonRecord> {

    private static final long serialVersionUID = 61808958;

    /**
     * The reference instance of <code>public.v_nbr_total_bon</code>
     */
    public static final VNbrTotalBon V_NBR_TOTAL_BON = new VNbrTotalBon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VNbrTotalBonRecord> getRecordType() {
        return VNbrTotalBonRecord.class;
    }

    /**
     * The column <code>public.v_nbr_total_bon.count</code>.
     */
    public final TableField<VNbrTotalBonRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_nbr_total_bon</code> table reference
     */
    public VNbrTotalBon() {
        this(DSL.name("v_nbr_total_bon"), null);
    }

    /**
     * Create an aliased <code>public.v_nbr_total_bon</code> table reference
     */
    public VNbrTotalBon(String alias) {
        this(DSL.name(alias), V_NBR_TOTAL_BON);
    }

    /**
     * Create an aliased <code>public.v_nbr_total_bon</code> table reference
     */
    public VNbrTotalBon(Name alias) {
        this(alias, V_NBR_TOTAL_BON);
    }

    private VNbrTotalBon(Name alias, Table<VNbrTotalBonRecord> aliased) {
        this(alias, aliased, null);
    }

    private VNbrTotalBon(Name alias, Table<VNbrTotalBonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrTotalBon as(String alias) {
        return new VNbrTotalBon(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrTotalBon as(Name alias) {
        return new VNbrTotalBon(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrTotalBon rename(String name) {
        return new VNbrTotalBon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrTotalBon rename(Name name) {
        return new VNbrTotalBon(name, null);
    }
}
