/*
 * This file is generated by jOOQ.
*/
package models.tables;


import javax.annotation.Generated;

import models.Public;
import models.tables.records.VNbrBonEnInstanceRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonEnInstance extends TableImpl<VNbrBonEnInstanceRecord> {

    private static final long serialVersionUID = 405206167;

    /**
     * The reference instance of <code>public.v_nbr_bon_en_instance</code>
     */
    public static final VNbrBonEnInstance V_NBR_BON_EN_INSTANCE = new VNbrBonEnInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VNbrBonEnInstanceRecord> getRecordType() {
        return VNbrBonEnInstanceRecord.class;
    }

    /**
     * The column <code>public.v_nbr_bon_en_instance.count</code>.
     */
    public final TableField<VNbrBonEnInstanceRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_nbr_bon_en_instance</code> table reference
     */
    public VNbrBonEnInstance() {
        this(DSL.name("v_nbr_bon_en_instance"), null);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_en_instance</code> table reference
     */
    public VNbrBonEnInstance(String alias) {
        this(DSL.name(alias), V_NBR_BON_EN_INSTANCE);
    }

    /**
     * Create an aliased <code>public.v_nbr_bon_en_instance</code> table reference
     */
    public VNbrBonEnInstance(Name alias) {
        this(alias, V_NBR_BON_EN_INSTANCE);
    }

    private VNbrBonEnInstance(Name alias, Table<VNbrBonEnInstanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private VNbrBonEnInstance(Name alias, Table<VNbrBonEnInstanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonEnInstance as(String alias) {
        return new VNbrBonEnInstance(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VNbrBonEnInstance as(Name alias) {
        return new VNbrBonEnInstance(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonEnInstance rename(String name) {
        return new VNbrBonEnInstance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VNbrBonEnInstance rename(Name name) {
        return new VNbrBonEnInstance(name, null);
    }
}
