/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VPharmacieRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPharmacie extends TableImpl<VPharmacieRecord> {

    private static final long serialVersionUID = -1252649381;

    /**
     * The reference instance of <code>public.v_pharmacie</code>
     */
    public static final VPharmacie V_PHARMACIE = new VPharmacie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPharmacieRecord> getRecordType() {
        return VPharmacieRecord.class;
    }

    /**
     * The column <code>public.v_pharmacie.id</code>.
     */
    public final TableField<VPharmacieRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_pharmacie.libelle</code>.
     */
    public final TableField<VPharmacieRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_pharmacie.who_done</code>.
     */
    public final TableField<VPharmacieRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_pharmacie.when_done</code>.
     */
    public final TableField<VPharmacieRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_pharmacie.is_deleted</code>.
     */
    public final TableField<VPharmacieRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_pharmacie.telephone</code>.
     */
    public final TableField<VPharmacieRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_pharmacie.statut_structure</code>.
     */
    public final TableField<VPharmacieRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_pharmacie.type_structure</code>.
     */
    public final TableField<VPharmacieRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_pharmacie.suspension</code>.
     */
    public final TableField<VPharmacieRecord, Boolean> SUSPENSION = createField("suspension", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_pharmacie.region</code>.
     */
    public final TableField<VPharmacieRecord, String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_pharmacie</code> table reference
     */
    public VPharmacie() {
        this(DSL.name("v_pharmacie"), null);
    }

    /**
     * Create an aliased <code>public.v_pharmacie</code> table reference
     */
    public VPharmacie(String alias) {
        this(DSL.name(alias), V_PHARMACIE);
    }

    /**
     * Create an aliased <code>public.v_pharmacie</code> table reference
     */
    public VPharmacie(Name alias) {
        this(alias, V_PHARMACIE);
    }

    private VPharmacie(Name alias, Table<VPharmacieRecord> aliased) {
        this(alias, aliased, null);
    }

    private VPharmacie(Name alias, Table<VPharmacieRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPharmacie as(String alias) {
        return new VPharmacie(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPharmacie as(Name alias) {
        return new VPharmacie(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VPharmacie rename(String name) {
        return new VPharmacie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPharmacie rename(Name name) {
        return new VPharmacie(name, null);
    }
}
