/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VReglementDetailsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementDetails extends TableImpl<VReglementDetailsRecord> {

    private static final long serialVersionUID = -575361365;

    /**
     * The reference instance of <code>public.v_reglement_details</code>
     */
    public static final VReglementDetails V_REGLEMENT_DETAILS = new VReglementDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VReglementDetailsRecord> getRecordType() {
        return VReglementDetailsRecord.class;
    }

    /**
     * The column <code>public.v_reglement_details.id</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.reglement</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> REGLEMENT = createField("reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.intitule</code>.
     */
    public final TableField<VReglementDetailsRecord, String> INTITULE = createField("intitule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.montant</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> MONTANT = createField("montant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.quantite</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> QUANTITE = createField("quantite", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.prix_unitaire</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> PRIX_UNITAIRE = createField("prix_unitaire", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.code_carnet</code>.
     */
    public final TableField<VReglementDetailsRecord, String> CODE_CARNET = createField("code_carnet", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.who_done</code>.
     */
    public final TableField<VReglementDetailsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.when_done</code>.
     */
    public final TableField<VReglementDetailsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_details.on_deleted</code>.
     */
    public final TableField<VReglementDetailsRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reglement_details.last_update</code>.
     */
    public final TableField<VReglementDetailsRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_details.ref_facture</code>.
     */
    public final TableField<VReglementDetailsRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.id_bon</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> ID_BON = createField("id_bon", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.nom_ad</code>.
     */
    public final TableField<VReglementDetailsRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.prenom_ad</code>.
     */
    public final TableField<VReglementDetailsRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.matricule</code>.
     */
    public final TableField<VReglementDetailsRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.structure</code>.
     */
    public final TableField<VReglementDetailsRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.taux_effectif</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> TAUX_EFFECTIF = createField("taux_effectif", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.date_payement</code>.
     */
    public final TableField<VReglementDetailsRecord, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_details.prestation</code>.
     */
    public final TableField<VReglementDetailsRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reglement_details.lien</code>.
     */
    public final TableField<VReglementDetailsRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement_details.is_confirmed_bon</code>.
     */
    public final TableField<VReglementDetailsRecord, Boolean> IS_CONFIRMED_BON = createField("is_confirmed_bon", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reglement_details.when_confirmed_bon</code>.
     */
    public final TableField<VReglementDetailsRecord, Timestamp> WHEN_CONFIRMED_BON = createField("when_confirmed_bon", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_details.date_expiration</code>.
     */
    public final TableField<VReglementDetailsRecord, Timestamp> DATE_EXPIRATION = createField("date_expiration", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement_details.total_couvert</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> TOTAL_COUVERT = createField("total_couvert", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement_details.total_restant</code>.
     */
    public final TableField<VReglementDetailsRecord, Long> TOTAL_RESTANT = createField("total_restant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_reglement_details</code> table reference
     */
    public VReglementDetails() {
        this(DSL.name("v_reglement_details"), null);
    }

    /**
     * Create an aliased <code>public.v_reglement_details</code> table reference
     */
    public VReglementDetails(String alias) {
        this(DSL.name(alias), V_REGLEMENT_DETAILS);
    }

    /**
     * Create an aliased <code>public.v_reglement_details</code> table reference
     */
    public VReglementDetails(Name alias) {
        this(alias, V_REGLEMENT_DETAILS);
    }

    private VReglementDetails(Name alias, Table<VReglementDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VReglementDetails(Name alias, Table<VReglementDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetails as(String alias) {
        return new VReglementDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglementDetails as(Name alias) {
        return new VReglementDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementDetails rename(String name) {
        return new VReglementDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglementDetails rename(Name name) {
        return new VReglementDetails(name, null);
    }
}
