/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VReglementRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglement extends TableImpl<VReglementRecord> {

    private static final long serialVersionUID = -2034936969;

    /**
     * The reference instance of <code>public.v_reglement</code>
     */
    public static final VReglement V_REGLEMENT = new VReglement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VReglementRecord> getRecordType() {
        return VReglementRecord.class;
    }

    /**
     * The column <code>public.v_reglement.id</code>.
     */
    public final TableField<VReglementRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.nom_ad</code>.
     */
    public final TableField<VReglementRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.prenom_ad</code>.
     */
    public final TableField<VReglementRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.id_adherent</code>.
     */
    public final TableField<VReglementRecord, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.matricule</code>.
     */
    public final TableField<VReglementRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.salaire_net</code>.
     */
    public final TableField<VReglementRecord, Long> SALAIRE_NET = createField("salaire_net", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.code_carnet</code>.
     */
    public final TableField<VReglementRecord, String> CODE_CARNET = createField("code_carnet", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.telephone</code>.
     */
    public final TableField<VReglementRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.pourcentage_total_retenue</code>.
     */
    public final TableField<VReglementRecord, Double> POURCENTAGE_TOTAL_RETENUE = createField("pourcentage_total_retenue", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_reglement.ref_facture</code>.
     */
    public final TableField<VReglementRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.id_struc</code>.
     */
    public final TableField<VReglementRecord, Long> ID_STRUC = createField("id_struc", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.structure</code>.
     */
    public final TableField<VReglementRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.date_payement</code>.
     */
    public final TableField<VReglementRecord, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement.who_done</code>.
     */
    public final TableField<VReglementRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.when_done</code>.
     */
    public final TableField<VReglementRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement.is_confirmed_bon</code>.
     */
    public final TableField<VReglementRecord, Boolean> IS_CONFIRMED_BON = createField("is_confirmed_bon", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reglement.when_confirmed_bon</code>.
     */
    public final TableField<VReglementRecord, Timestamp> WHEN_CONFIRMED_BON = createField("when_confirmed_bon", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement.date_expiration</code>.
     */
    public final TableField<VReglementRecord, Timestamp> DATE_EXPIRATION = createField("date_expiration", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reglement.type_reglement</code>.
     */
    public final TableField<VReglementRecord, String> TYPE_REGLEMENT = createField("type_reglement", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.annee</code>.
     */
    public final TableField<VReglementRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.on_deleted</code>.
     */
    public final TableField<VReglementRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reglement.id_prestation</code>.
     */
    public final TableField<VReglementRecord, Long> ID_PRESTATION = createField("id_prestation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.prestation</code>.
     */
    public final TableField<VReglementRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reglement.couverture</code>.
     */
    public final TableField<VReglementRecord, String> COUVERTURE = createField("couverture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reglement.taux_public</code>.
     */
    public final TableField<VReglementRecord, String> TAUX_PUBLIC = createField("taux_public", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.taux_prive</code>.
     */
    public final TableField<VReglementRecord, String> TAUX_PRIVE = createField("taux_prive", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.type_structure</code>.
     */
    public final TableField<VReglementRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.statut_structure</code>.
     */
    public final TableField<VReglementRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.nom_ay</code>.
     */
    public final TableField<VReglementRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.lien</code>.
     */
    public final TableField<VReglementRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.genre</code>.
     */
    public final TableField<VReglementRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.ayant_droit</code>.
     */
    public final TableField<VReglementRecord, Long> AYANT_DROIT = createField("ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.montant_total</code>.
     */
    public final TableField<VReglementRecord, Long> MONTANT_TOTAL = createField("montant_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.taux_couverture_effectif</code>.
     */
    public final TableField<VReglementRecord, String> TAUX_COUVERTURE_EFFECTIF = createField("taux_couverture_effectif", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reglement.montant_reglement</code>.
     */
    public final TableField<VReglementRecord, Long> MONTANT_REGLEMENT = createField("montant_reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.montant_paye</code>.
     */
    public final TableField<VReglementRecord, Long> MONTANT_PAYE = createField("montant_paye", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reglement.id_structure</code>.
     */
    public final TableField<VReglementRecord, Long> ID_STRUCTURE = createField("id_structure", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_reglement</code> table reference
     */
    public VReglement() {
        this(DSL.name("v_reglement"), null);
    }

    /**
     * Create an aliased <code>public.v_reglement</code> table reference
     */
    public VReglement(String alias) {
        this(DSL.name(alias), V_REGLEMENT);
    }

    /**
     * Create an aliased <code>public.v_reglement</code> table reference
     */
    public VReglement(Name alias) {
        this(alias, V_REGLEMENT);
    }

    private VReglement(Name alias, Table<VReglementRecord> aliased) {
        this(alias, aliased, null);
    }

    private VReglement(Name alias, Table<VReglementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglement as(String alias) {
        return new VReglement(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VReglement as(Name alias) {
        return new VReglement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglement rename(String name) {
        return new VReglement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VReglement rename(Name name) {
        return new VReglement(name, null);
    }
}
