/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VRegBonCommandeRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VRegBonCommande extends TableImpl<VRegBonCommandeRecord> {

    private static final long serialVersionUID = -581672945;

    /**
     * The reference instance of <code>public.v_reg_bon_commande</code>
     */
    public static final VRegBonCommande V_REG_BON_COMMANDE = new VRegBonCommande();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VRegBonCommandeRecord> getRecordType() {
        return VRegBonCommandeRecord.class;
    }

    /**
     * The column <code>public.v_reg_bon_commande.id</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.nom_ad</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.prenom_ad</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.id_adherent</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.matricule</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.ref_facture</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.structure</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.date_payement</code>.
     */
    public final TableField<VRegBonCommandeRecord, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.who_done</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.when_done</code>.
     */
    public final TableField<VRegBonCommandeRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.is_confirmed_bon</code>.
     */
    public final TableField<VRegBonCommandeRecord, Boolean> IS_CONFIRMED_BON = createField("is_confirmed_bon", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.when_confirmed_bon</code>.
     */
    public final TableField<VRegBonCommandeRecord, Timestamp> WHEN_CONFIRMED_BON = createField("when_confirmed_bon", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.date_expiration</code>.
     */
    public final TableField<VRegBonCommandeRecord, Timestamp> DATE_EXPIRATION = createField("date_expiration", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.type_reglement</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> TYPE_REGLEMENT = createField("type_reglement", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.annee</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.on_deleted</code>.
     */
    public final TableField<VRegBonCommandeRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.prestation</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reg_bon_commande.couverture</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> COUVERTURE = createField("couverture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reg_bon_commande.taux_public</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> TAUX_PUBLIC = createField("taux_public", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.taux_prive</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> TAUX_PRIVE = createField("taux_prive", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.type_structure</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.statut_structure</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.nom_ay</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.lien</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.genre</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.ayant_droit</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> AYANT_DROIT = createField("ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.montant_total</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> MONTANT_TOTAL = createField("montant_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.taux_couverture_effectif</code>.
     */
    public final TableField<VRegBonCommandeRecord, String> TAUX_COUVERTURE_EFFECTIF = createField("taux_couverture_effectif", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.montant_reglement</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> MONTANT_REGLEMENT = createField("montant_reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.montant_paye</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> MONTANT_PAYE = createField("montant_paye", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_bon_commande.id_structure</code>.
     */
    public final TableField<VRegBonCommandeRecord, Long> ID_STRUCTURE = createField("id_structure", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_reg_bon_commande</code> table reference
     */
    public VRegBonCommande() {
        this(DSL.name("v_reg_bon_commande"), null);
    }

    /**
     * Create an aliased <code>public.v_reg_bon_commande</code> table reference
     */
    public VRegBonCommande(String alias) {
        this(DSL.name(alias), V_REG_BON_COMMANDE);
    }

    /**
     * Create an aliased <code>public.v_reg_bon_commande</code> table reference
     */
    public VRegBonCommande(Name alias) {
        this(alias, V_REG_BON_COMMANDE);
    }

    private VRegBonCommande(Name alias, Table<VRegBonCommandeRecord> aliased) {
        this(alias, aliased, null);
    }

    private VRegBonCommande(Name alias, Table<VRegBonCommandeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegBonCommande as(String alias) {
        return new VRegBonCommande(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegBonCommande as(Name alias) {
        return new VRegBonCommande(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VRegBonCommande rename(String name) {
        return new VRegBonCommande(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VRegBonCommande rename(Name name) {
        return new VRegBonCommande(name, null);
    }
}
