/*
 * This file is generated by jOOQ.
*/
package models.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.Public;
import models.tables.records.VRegPriseEnChargeRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VRegPriseEnCharge extends TableImpl<VRegPriseEnChargeRecord> {

    private static final long serialVersionUID = -660675296;

    /**
     * The reference instance of <code>public.v_reg_prise_en_charge</code>
     */
    public static final VRegPriseEnCharge V_REG_PRISE_EN_CHARGE = new VRegPriseEnCharge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VRegPriseEnChargeRecord> getRecordType() {
        return VRegPriseEnChargeRecord.class;
    }

    /**
     * The column <code>public.v_reg_prise_en_charge.id</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.nom_ad</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> NOM_AD = createField("nom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.prenom_ad</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> PRENOM_AD = createField("prenom_ad", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.id_adherent</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> ID_ADHERENT = createField("id_adherent", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.matricule</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> MATRICULE = createField("matricule", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.ref_facture</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> REF_FACTURE = createField("ref_facture", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.structure</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> STRUCTURE = createField("structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.date_payement</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Timestamp> DATE_PAYEMENT = createField("date_payement", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.who_done</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.when_done</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.is_confirmed_bon</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Boolean> IS_CONFIRMED_BON = createField("is_confirmed_bon", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.when_confirmed_bon</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Timestamp> WHEN_CONFIRMED_BON = createField("when_confirmed_bon", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.date_expiration</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Timestamp> DATE_EXPIRATION = createField("date_expiration", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.type_reglement</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> TYPE_REGLEMENT = createField("type_reglement", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.annee</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> ANNEE = createField("annee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.on_deleted</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Boolean> ON_DELETED = createField("on_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.prestation</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> PRESTATION = createField("prestation", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.couverture</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> COUVERTURE = createField("couverture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.taux_public</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> TAUX_PUBLIC = createField("taux_public", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.taux_prive</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> TAUX_PRIVE = createField("taux_prive", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.type_structure</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> TYPE_STRUCTURE = createField("type_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.statut_structure</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> STATUT_STRUCTURE = createField("statut_structure", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.nom_ay</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> NOM_AY = createField("nom_ay", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.lien</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> LIEN = createField("lien", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.genre</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.ayant_droit</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> AYANT_DROIT = createField("ayant_droit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.montant_total</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> MONTANT_TOTAL = createField("montant_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.taux_couverture_effectif</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, String> TAUX_COUVERTURE_EFFECTIF = createField("taux_couverture_effectif", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.montant_reglement</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> MONTANT_REGLEMENT = createField("montant_reglement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.montant_paye</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> MONTANT_PAYE = createField("montant_paye", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_reg_prise_en_charge.id_structure</code>.
     */
    public final TableField<VRegPriseEnChargeRecord, Long> ID_STRUCTURE = createField("id_structure", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_reg_prise_en_charge</code> table reference
     */
    public VRegPriseEnCharge() {
        this(DSL.name("v_reg_prise_en_charge"), null);
    }

    /**
     * Create an aliased <code>public.v_reg_prise_en_charge</code> table reference
     */
    public VRegPriseEnCharge(String alias) {
        this(DSL.name(alias), V_REG_PRISE_EN_CHARGE);
    }

    /**
     * Create an aliased <code>public.v_reg_prise_en_charge</code> table reference
     */
    public VRegPriseEnCharge(Name alias) {
        this(alias, V_REG_PRISE_EN_CHARGE);
    }

    private VRegPriseEnCharge(Name alias, Table<VRegPriseEnChargeRecord> aliased) {
        this(alias, aliased, null);
    }

    private VRegPriseEnCharge(Name alias, Table<VRegPriseEnChargeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegPriseEnCharge as(String alias) {
        return new VRegPriseEnCharge(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegPriseEnCharge as(Name alias) {
        return new VRegPriseEnCharge(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VRegPriseEnCharge rename(String name) {
        return new VRegPriseEnCharge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VRegPriseEnCharge rename(Name name) {
        return new VRegPriseEnCharge(name, null);
    }
}
