/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Table stockant les données d'étude de consommations des bons de commande
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudeConsommations implements Serializable {

    private static final long serialVersionUID = 301437088;

    private Long       id;
    private String     numeroCarnet;
    private String     codeAgent;
    private String     nomPrenoms;
    private BigDecimal agent;
    private BigDecimal conjoint;
    private BigDecimal enfants;
    private BigDecimal pere;
    private BigDecimal mere;
    private BigDecimal salaireBase;
    private BigDecimal pourcentageRetenir;
    private BigDecimal retenueMensuelle;
    private BigDecimal creditAnnuel;
    private BigDecimal creditAnnuelX2;
    private BigDecimal consommationBons;
    private BigDecimal consommationPc;
    private BigDecimal remboursement;
    private BigDecimal totalConsommation;
    private BigDecimal solde_1;
    private BigDecimal solde_2;
    private String     statutAvertissement;
    private String     statutSuspension;
    private String     fichierSource;
    private Timestamp  dateImport;
    private String     utilisateurImport;

    public EtudeConsommations() {}

    public EtudeConsommations(EtudeConsommations value) {
        this.id = value.id;
        this.numeroCarnet = value.numeroCarnet;
        this.codeAgent = value.codeAgent;
        this.nomPrenoms = value.nomPrenoms;
        this.agent = value.agent;
        this.conjoint = value.conjoint;
        this.enfants = value.enfants;
        this.pere = value.pere;
        this.mere = value.mere;
        this.salaireBase = value.salaireBase;
        this.pourcentageRetenir = value.pourcentageRetenir;
        this.retenueMensuelle = value.retenueMensuelle;
        this.creditAnnuel = value.creditAnnuel;
        this.creditAnnuelX2 = value.creditAnnuelX2;
        this.consommationBons = value.consommationBons;
        this.consommationPc = value.consommationPc;
        this.remboursement = value.remboursement;
        this.totalConsommation = value.totalConsommation;
        this.solde_1 = value.solde_1;
        this.solde_2 = value.solde_2;
        this.statutAvertissement = value.statutAvertissement;
        this.statutSuspension = value.statutSuspension;
        this.fichierSource = value.fichierSource;
        this.dateImport = value.dateImport;
        this.utilisateurImport = value.utilisateurImport;
    }

    public EtudeConsommations(
        Long       id,
        String     numeroCarnet,
        String     codeAgent,
        String     nomPrenoms,
        BigDecimal agent,
        BigDecimal conjoint,
        BigDecimal enfants,
        BigDecimal pere,
        BigDecimal mere,
        BigDecimal salaireBase,
        BigDecimal pourcentageRetenir,
        BigDecimal retenueMensuelle,
        BigDecimal creditAnnuel,
        BigDecimal creditAnnuelX2,
        BigDecimal consommationBons,
        BigDecimal consommationPc,
        BigDecimal remboursement,
        BigDecimal totalConsommation,
        BigDecimal solde_1,
        BigDecimal solde_2,
        String     statutAvertissement,
        String     statutSuspension,
        String     fichierSource,
        Timestamp  dateImport,
        String     utilisateurImport
    ) {
        this.id = id;
        this.numeroCarnet = numeroCarnet;
        this.codeAgent = codeAgent;
        this.nomPrenoms = nomPrenoms;
        this.agent = agent;
        this.conjoint = conjoint;
        this.enfants = enfants;
        this.pere = pere;
        this.mere = mere;
        this.salaireBase = salaireBase;
        this.pourcentageRetenir = pourcentageRetenir;
        this.retenueMensuelle = retenueMensuelle;
        this.creditAnnuel = creditAnnuel;
        this.creditAnnuelX2 = creditAnnuelX2;
        this.consommationBons = consommationBons;
        this.consommationPc = consommationPc;
        this.remboursement = remboursement;
        this.totalConsommation = totalConsommation;
        this.solde_1 = solde_1;
        this.solde_2 = solde_2;
        this.statutAvertissement = statutAvertissement;
        this.statutSuspension = statutSuspension;
        this.fichierSource = fichierSource;
        this.dateImport = dateImport;
        this.utilisateurImport = utilisateurImport;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumeroCarnet() {
        return this.numeroCarnet;
    }

    public void setNumeroCarnet(String numeroCarnet) {
        this.numeroCarnet = numeroCarnet;
    }

    public String getCodeAgent() {
        return this.codeAgent;
    }

    public void setCodeAgent(String codeAgent) {
        this.codeAgent = codeAgent;
    }

    public String getNomPrenoms() {
        return this.nomPrenoms;
    }

    public void setNomPrenoms(String nomPrenoms) {
        this.nomPrenoms = nomPrenoms;
    }

    public BigDecimal getAgent() {
        return this.agent;
    }

    public void setAgent(BigDecimal agent) {
        this.agent = agent;
    }

    public BigDecimal getConjoint() {
        return this.conjoint;
    }

    public void setConjoint(BigDecimal conjoint) {
        this.conjoint = conjoint;
    }

    public BigDecimal getEnfants() {
        return this.enfants;
    }

    public void setEnfants(BigDecimal enfants) {
        this.enfants = enfants;
    }

    public BigDecimal getPere() {
        return this.pere;
    }

    public void setPere(BigDecimal pere) {
        this.pere = pere;
    }

    public BigDecimal getMere() {
        return this.mere;
    }

    public void setMere(BigDecimal mere) {
        this.mere = mere;
    }

    public BigDecimal getSalaireBase() {
        return this.salaireBase;
    }

    public void setSalaireBase(BigDecimal salaireBase) {
        this.salaireBase = salaireBase;
    }

    public BigDecimal getPourcentageRetenir() {
        return this.pourcentageRetenir;
    }

    public void setPourcentageRetenir(BigDecimal pourcentageRetenir) {
        this.pourcentageRetenir = pourcentageRetenir;
    }

    public BigDecimal getRetenueMensuelle() {
        return this.retenueMensuelle;
    }

    public void setRetenueMensuelle(BigDecimal retenueMensuelle) {
        this.retenueMensuelle = retenueMensuelle;
    }

    public BigDecimal getCreditAnnuel() {
        return this.creditAnnuel;
    }

    public void setCreditAnnuel(BigDecimal creditAnnuel) {
        this.creditAnnuel = creditAnnuel;
    }

    public BigDecimal getCreditAnnuelX2() {
        return this.creditAnnuelX2;
    }

    public void setCreditAnnuelX2(BigDecimal creditAnnuelX2) {
        this.creditAnnuelX2 = creditAnnuelX2;
    }

    public BigDecimal getConsommationBons() {
        return this.consommationBons;
    }

    public void setConsommationBons(BigDecimal consommationBons) {
        this.consommationBons = consommationBons;
    }

    public BigDecimal getConsommationPc() {
        return this.consommationPc;
    }

    public void setConsommationPc(BigDecimal consommationPc) {
        this.consommationPc = consommationPc;
    }

    public BigDecimal getRemboursement() {
        return this.remboursement;
    }

    public void setRemboursement(BigDecimal remboursement) {
        this.remboursement = remboursement;
    }

    public BigDecimal getTotalConsommation() {
        return this.totalConsommation;
    }

    public void setTotalConsommation(BigDecimal totalConsommation) {
        this.totalConsommation = totalConsommation;
    }

    public BigDecimal getSolde_1() {
        return this.solde_1;
    }

    public void setSolde_1(BigDecimal solde_1) {
        this.solde_1 = solde_1;
    }

    public BigDecimal getSolde_2() {
        return this.solde_2;
    }

    public void setSolde_2(BigDecimal solde_2) {
        this.solde_2 = solde_2;
    }

    public String getStatutAvertissement() {
        return this.statutAvertissement;
    }

    public void setStatutAvertissement(String statutAvertissement) {
        this.statutAvertissement = statutAvertissement;
    }

    public String getStatutSuspension() {
        return this.statutSuspension;
    }

    public void setStatutSuspension(String statutSuspension) {
        this.statutSuspension = statutSuspension;
    }

    public String getFichierSource() {
        return this.fichierSource;
    }

    public void setFichierSource(String fichierSource) {
        this.fichierSource = fichierSource;
    }

    public Timestamp getDateImport() {
        return this.dateImport;
    }

    public void setDateImport(Timestamp dateImport) {
        this.dateImport = dateImport;
    }

    public String getUtilisateurImport() {
        return this.utilisateurImport;
    }

    public void setUtilisateurImport(String utilisateurImport) {
        this.utilisateurImport = utilisateurImport;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EtudeConsommations (");

        sb.append(id);
        sb.append(", ").append(numeroCarnet);
        sb.append(", ").append(codeAgent);
        sb.append(", ").append(nomPrenoms);
        sb.append(", ").append(agent);
        sb.append(", ").append(conjoint);
        sb.append(", ").append(enfants);
        sb.append(", ").append(pere);
        sb.append(", ").append(mere);
        sb.append(", ").append(salaireBase);
        sb.append(", ").append(pourcentageRetenir);
        sb.append(", ").append(retenueMensuelle);
        sb.append(", ").append(creditAnnuel);
        sb.append(", ").append(creditAnnuelX2);
        sb.append(", ").append(consommationBons);
        sb.append(", ").append(consommationPc);
        sb.append(", ").append(remboursement);
        sb.append(", ").append(totalConsommation);
        sb.append(", ").append(solde_1);
        sb.append(", ").append(solde_2);
        sb.append(", ").append(statutAvertissement);
        sb.append(", ").append(statutSuspension);
        sb.append(", ").append(fichierSource);
        sb.append(", ").append(dateImport);
        sb.append(", ").append(utilisateurImport);

        sb.append(")");
        return sb.toString();
    }
}
