/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification implements Serializable {

    private static final long serialVersionUID = 1494747764;

    private Long           id;
    private Long           adherent;
    private String         numTel;
    private String         numBon;
    private String         message;
    private OffsetDateTime whenDone;
    private String         whoDone;

    public Notification() {}

    public Notification(Notification value) {
        this.id = value.id;
        this.adherent = value.adherent;
        this.numTel = value.numTel;
        this.numBon = value.numBon;
        this.message = value.message;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
    }

    public Notification(
        Long           id,
        Long           adherent,
        String         numTel,
        String         numBon,
        String         message,
        OffsetDateTime whenDone,
        String         whoDone
    ) {
        this.id = id;
        this.adherent = adherent;
        this.numTel = numTel;
        this.numBon = numBon;
        this.message = message;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdherent() {
        return this.adherent;
    }

    public void setAdherent(Long adherent) {
        this.adherent = adherent;
    }

    public String getNumTel() {
        return this.numTel;
    }

    public void setNumTel(String numTel) {
        this.numTel = numTel;
    }

    public String getNumBon() {
        return this.numBon;
    }

    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public OffsetDateTime getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(OffsetDateTime whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notification (");

        sb.append(id);
        sb.append(", ").append(adherent);
        sb.append(", ").append(numTel);
        sb.append(", ").append(numBon);
        sb.append(", ").append(message);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);

        sb.append(")");
        return sb.toString();
    }
}
