/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtpMessage implements Serializable {

    private static final long serialVersionUID = -1410641055;

    private Long      id;
    private String    phone;
    private String    code;
    private String    message;
    private Long      bonCommande;
    private Timestamp createdAt;
    private Timestamp expiresAt;
    private Boolean   isUsed;
    private Boolean   isSent;
    private String    sentResponse;
    private Integer   attemptCount;
    private String    context;

    public OtpMessage() {}

    public OtpMessage(OtpMessage value) {
        this.id = value.id;
        this.phone = value.phone;
        this.code = value.code;
        this.message = value.message;
        this.bonCommande = value.bonCommande;
        this.createdAt = value.createdAt;
        this.expiresAt = value.expiresAt;
        this.isUsed = value.isUsed;
        this.isSent = value.isSent;
        this.sentResponse = value.sentResponse;
        this.attemptCount = value.attemptCount;
        this.context = value.context;
    }

    public OtpMessage(
        Long      id,
        String    phone,
        String    code,
        String    message,
        Long      bonCommande,
        Timestamp createdAt,
        Timestamp expiresAt,
        Boolean   isUsed,
        Boolean   isSent,
        String    sentResponse,
        Integer   attemptCount,
        String    context
    ) {
        this.id = id;
        this.phone = phone;
        this.code = code;
        this.message = message;
        this.bonCommande = bonCommande;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.isUsed = isUsed;
        this.isSent = isSent;
        this.sentResponse = sentResponse;
        this.attemptCount = attemptCount;
        this.context = context;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getBonCommande() {
        return this.bonCommande;
    }

    public void setBonCommande(Long bonCommande) {
        this.bonCommande = bonCommande;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getExpiresAt() {
        return this.expiresAt;
    }

    public void setExpiresAt(Timestamp expiresAt) {
        this.expiresAt = expiresAt;
    }

    public Boolean getIsUsed() {
        return this.isUsed;
    }

    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    public Boolean getIsSent() {
        return this.isSent;
    }

    public void setIsSent(Boolean isSent) {
        this.isSent = isSent;
    }

    public String getSentResponse() {
        return this.sentResponse;
    }

    public void setSentResponse(String sentResponse) {
        this.sentResponse = sentResponse;
    }

    public Integer getAttemptCount() {
        return this.attemptCount;
    }

    public void setAttemptCount(Integer attemptCount) {
        this.attemptCount = attemptCount;
    }

    public String getContext() {
        return this.context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtpMessage (");

        sb.append(id);
        sb.append(", ").append(phone);
        sb.append(", ").append(code);
        sb.append(", ").append(message);
        sb.append(", ").append(bonCommande);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(isUsed);
        sb.append(", ").append(isSent);
        sb.append(", ").append(sentResponse);
        sb.append(", ").append(attemptCount);
        sb.append(", ").append(context);

        sb.append(")");
        return sb.toString();
    }
}
