/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reglement implements Serializable {

    private static final long serialVersionUID = -468458042;

    private Long      id;
    private Long      adherent;
    private String    refFacture;
    private Long      structure;
    private Timestamp datePayement;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;
    private Long      typePrestation;
    private Long      ayantDroit;
    private String    structureEmettriceRembourssement;
    private String    telStructureEmettrice;
    private String    numBon;
    private Boolean   isConfirmedBon;
    private Timestamp whenConfirmedBon;
    private Timestamp dateExpiration;
    private String    typeReglement;

    public Reglement() {}

    public Reglement(Reglement value) {
        this.id = value.id;
        this.adherent = value.adherent;
        this.refFacture = value.refFacture;
        this.structure = value.structure;
        this.datePayement = value.datePayement;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
        this.typePrestation = value.typePrestation;
        this.ayantDroit = value.ayantDroit;
        this.structureEmettriceRembourssement = value.structureEmettriceRembourssement;
        this.telStructureEmettrice = value.telStructureEmettrice;
        this.numBon = value.numBon;
        this.isConfirmedBon = value.isConfirmedBon;
        this.whenConfirmedBon = value.whenConfirmedBon;
        this.dateExpiration = value.dateExpiration;
        this.typeReglement = value.typeReglement;
    }

    public Reglement(
        Long      id,
        Long      adherent,
        String    refFacture,
        Long      structure,
        Timestamp datePayement,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted,
        Long      typePrestation,
        Long      ayantDroit,
        String    structureEmettriceRembourssement,
        String    telStructureEmettrice,
        String    numBon,
        Boolean   isConfirmedBon,
        Timestamp whenConfirmedBon,
        Timestamp dateExpiration,
        String    typeReglement
    ) {
        this.id = id;
        this.adherent = adherent;
        this.refFacture = refFacture;
        this.structure = structure;
        this.datePayement = datePayement;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
        this.typePrestation = typePrestation;
        this.ayantDroit = ayantDroit;
        this.structureEmettriceRembourssement = structureEmettriceRembourssement;
        this.telStructureEmettrice = telStructureEmettrice;
        this.numBon = numBon;
        this.isConfirmedBon = isConfirmedBon;
        this.whenConfirmedBon = whenConfirmedBon;
        this.dateExpiration = dateExpiration;
        this.typeReglement = typeReglement;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdherent() {
        return this.adherent;
    }

    public void setAdherent(Long adherent) {
        this.adherent = adherent;
    }

    public String getRefFacture() {
        return this.refFacture;
    }

    public void setRefFacture(String refFacture) {
        this.refFacture = refFacture;
    }

    public Long getStructure() {
        return this.structure;
    }

    public void setStructure(Long structure) {
        this.structure = structure;
    }

    public Timestamp getDatePayement() {
        return this.datePayement;
    }

    public void setDatePayement(Timestamp datePayement) {
        this.datePayement = datePayement;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public Long getTypePrestation() {
        return this.typePrestation;
    }

    public void setTypePrestation(Long typePrestation) {
        this.typePrestation = typePrestation;
    }

    public Long getAyantDroit() {
        return this.ayantDroit;
    }

    public void setAyantDroit(Long ayantDroit) {
        this.ayantDroit = ayantDroit;
    }

    public String getStructureEmettriceRembourssement() {
        return this.structureEmettriceRembourssement;
    }

    public void setStructureEmettriceRembourssement(String structureEmettriceRembourssement) {
        this.structureEmettriceRembourssement = structureEmettriceRembourssement;
    }

    public String getTelStructureEmettrice() {
        return this.telStructureEmettrice;
    }

    public void setTelStructureEmettrice(String telStructureEmettrice) {
        this.telStructureEmettrice = telStructureEmettrice;
    }

    public String getNumBon() {
        return this.numBon;
    }

    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    public Boolean getIsConfirmedBon() {
        return this.isConfirmedBon;
    }

    public void setIsConfirmedBon(Boolean isConfirmedBon) {
        this.isConfirmedBon = isConfirmedBon;
    }

    public Timestamp getWhenConfirmedBon() {
        return this.whenConfirmedBon;
    }

    public void setWhenConfirmedBon(Timestamp whenConfirmedBon) {
        this.whenConfirmedBon = whenConfirmedBon;
    }

    public Timestamp getDateExpiration() {
        return this.dateExpiration;
    }

    public void setDateExpiration(Timestamp dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    public String getTypeReglement() {
        return this.typeReglement;
    }

    public void setTypeReglement(String typeReglement) {
        this.typeReglement = typeReglement;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reglement (");

        sb.append(id);
        sb.append(", ").append(adherent);
        sb.append(", ").append(refFacture);
        sb.append(", ").append(structure);
        sb.append(", ").append(datePayement);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(typePrestation);
        sb.append(", ").append(ayantDroit);
        sb.append(", ").append(structureEmettriceRembourssement);
        sb.append(", ").append(telStructureEmettrice);
        sb.append(", ").append(numBon);
        sb.append(", ").append(isConfirmedBon);
        sb.append(", ").append(whenConfirmedBon);
        sb.append(", ").append(dateExpiration);
        sb.append(", ").append(typeReglement);

        sb.append(")");
        return sb.toString();
    }
}
