/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePrestation implements Serializable {

    private static final long serialVersionUID = -142325121;

    private Long    id;
    private String  prestation;
    private String  couverture;
    private Boolean onDeleted;
    private String  tauxPublic;
    private String  tauxPrive;

    public TypePrestation() {}

    public TypePrestation(TypePrestation value) {
        this.id = value.id;
        this.prestation = value.prestation;
        this.couverture = value.couverture;
        this.onDeleted = value.onDeleted;
        this.tauxPublic = value.tauxPublic;
        this.tauxPrive = value.tauxPrive;
    }

    public TypePrestation(
        Long    id,
        String  prestation,
        String  couverture,
        Boolean onDeleted,
        String  tauxPublic,
        String  tauxPrive
    ) {
        this.id = id;
        this.prestation = prestation;
        this.couverture = couverture;
        this.onDeleted = onDeleted;
        this.tauxPublic = tauxPublic;
        this.tauxPrive = tauxPrive;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPrestation() {
        return this.prestation;
    }

    public void setPrestation(String prestation) {
        this.prestation = prestation;
    }

    public String getCouverture() {
        return this.couverture;
    }

    public void setCouverture(String couverture) {
        this.couverture = couverture;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public String getTauxPublic() {
        return this.tauxPublic;
    }

    public void setTauxPublic(String tauxPublic) {
        this.tauxPublic = tauxPublic;
    }

    public String getTauxPrive() {
        return this.tauxPrive;
    }

    public void setTauxPrive(String tauxPrive) {
        this.tauxPrive = tauxPrive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TypePrestation (");

        sb.append(id);
        sb.append(", ").append(prestation);
        sb.append(", ").append(couverture);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(tauxPublic);
        sb.append(", ").append(tauxPrive);

        sb.append(")");
        return sb.toString();
    }
}
