/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 616107892;

    private Long      id;
    private String    login;
    private String    droit;
    private Boolean   etat;
    private String    passe;
    private String    nomPrenom;
    private String    photo;
    private Boolean   connectFirst;
    private String    whoDone;
    private Timestamp whenDone;
    private Long      regionCode;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.login = value.login;
        this.droit = value.droit;
        this.etat = value.etat;
        this.passe = value.passe;
        this.nomPrenom = value.nomPrenom;
        this.photo = value.photo;
        this.connectFirst = value.connectFirst;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.regionCode = value.regionCode;
    }

    public Users(
        Long      id,
        String    login,
        String    droit,
        Boolean   etat,
        String    passe,
        String    nomPrenom,
        String    photo,
        Boolean   connectFirst,
        String    whoDone,
        Timestamp whenDone,
        Long      regionCode
    ) {
        this.id = id;
        this.login = login;
        this.droit = droit;
        this.etat = etat;
        this.passe = passe;
        this.nomPrenom = nomPrenom;
        this.photo = photo;
        this.connectFirst = connectFirst;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.regionCode = regionCode;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getDroit() {
        return this.droit;
    }

    public void setDroit(String droit) {
        this.droit = droit;
    }

    public Boolean getEtat() {
        return this.etat;
    }

    public void setEtat(Boolean etat) {
        this.etat = etat;
    }

    public String getPasse() {
        return this.passe;
    }

    public void setPasse(String passe) {
        this.passe = passe;
    }

    public String getNomPrenom() {
        return this.nomPrenom;
    }

    public void setNomPrenom(String nomPrenom) {
        this.nomPrenom = nomPrenom;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Boolean getConnectFirst() {
        return this.connectFirst;
    }

    public void setConnectFirst(Boolean connectFirst) {
        this.connectFirst = connectFirst;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Long getRegionCode() {
        return this.regionCode;
    }

    public void setRegionCode(Long regionCode) {
        this.regionCode = regionCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(droit);
        sb.append(", ").append(etat);
        sb.append(", ").append(passe);
        sb.append(", ").append(nomPrenom);
        sb.append(", ").append(photo);
        sb.append(", ").append(connectFirst);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(regionCode);

        sb.append(")");
        return sb.toString();
    }
}
