/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VBonDeCommande implements Serializable {

    private static final long serialVersionUID = 1499075958;

    private Long      id;
    private String    nomAd;
    private String    prenomAd;
    private String    codeCarnet;
    private Long      idAdherent;
    private String    matricule;
    private String    refFacture;
    private String    structure;
    private Timestamp datePayement;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   isConfirmedBon;
    private Timestamp whenConfirmedBon;
    private String    annee;
    private Boolean   onDeleted;
    private String    prestation;
    private String    couverture;
    private String    nomAy;
    private String    lien;
    private String    genre;
    private Long      ayantDroit;
    private Long      montantTotal;
    private Long      montantReglement;
    private Long      montantPaye;
    private Long      idStructure;

    public VBonDeCommande() {}

    public VBonDeCommande(VBonDeCommande value) {
        this.id = value.id;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.codeCarnet = value.codeCarnet;
        this.idAdherent = value.idAdherent;
        this.matricule = value.matricule;
        this.refFacture = value.refFacture;
        this.structure = value.structure;
        this.datePayement = value.datePayement;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.isConfirmedBon = value.isConfirmedBon;
        this.whenConfirmedBon = value.whenConfirmedBon;
        this.annee = value.annee;
        this.onDeleted = value.onDeleted;
        this.prestation = value.prestation;
        this.couverture = value.couverture;
        this.nomAy = value.nomAy;
        this.lien = value.lien;
        this.genre = value.genre;
        this.ayantDroit = value.ayantDroit;
        this.montantTotal = value.montantTotal;
        this.montantReglement = value.montantReglement;
        this.montantPaye = value.montantPaye;
        this.idStructure = value.idStructure;
    }

    public VBonDeCommande(
        Long      id,
        String    nomAd,
        String    prenomAd,
        String    codeCarnet,
        Long      idAdherent,
        String    matricule,
        String    refFacture,
        String    structure,
        Timestamp datePayement,
        String    whoDone,
        Timestamp whenDone,
        Boolean   isConfirmedBon,
        Timestamp whenConfirmedBon,
        String    annee,
        Boolean   onDeleted,
        String    prestation,
        String    couverture,
        String    nomAy,
        String    lien,
        String    genre,
        Long      ayantDroit,
        Long      montantTotal,
        Long      montantReglement,
        Long      montantPaye,
        Long      idStructure
    ) {
        this.id = id;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.codeCarnet = codeCarnet;
        this.idAdherent = idAdherent;
        this.matricule = matricule;
        this.refFacture = refFacture;
        this.structure = structure;
        this.datePayement = datePayement;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.isConfirmedBon = isConfirmedBon;
        this.whenConfirmedBon = whenConfirmedBon;
        this.annee = annee;
        this.onDeleted = onDeleted;
        this.prestation = prestation;
        this.couverture = couverture;
        this.nomAy = nomAy;
        this.lien = lien;
        this.genre = genre;
        this.ayantDroit = ayantDroit;
        this.montantTotal = montantTotal;
        this.montantReglement = montantReglement;
        this.montantPaye = montantPaye;
        this.idStructure = idStructure;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getCodeCarnet() {
        return this.codeCarnet;
    }

    public void setCodeCarnet(String codeCarnet) {
        this.codeCarnet = codeCarnet;
    }

    public Long getIdAdherent() {
        return this.idAdherent;
    }

    public void setIdAdherent(Long idAdherent) {
        this.idAdherent = idAdherent;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getRefFacture() {
        return this.refFacture;
    }

    public void setRefFacture(String refFacture) {
        this.refFacture = refFacture;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public Timestamp getDatePayement() {
        return this.datePayement;
    }

    public void setDatePayement(Timestamp datePayement) {
        this.datePayement = datePayement;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getIsConfirmedBon() {
        return this.isConfirmedBon;
    }

    public void setIsConfirmedBon(Boolean isConfirmedBon) {
        this.isConfirmedBon = isConfirmedBon;
    }

    public Timestamp getWhenConfirmedBon() {
        return this.whenConfirmedBon;
    }

    public void setWhenConfirmedBon(Timestamp whenConfirmedBon) {
        this.whenConfirmedBon = whenConfirmedBon;
    }

    public String getAnnee() {
        return this.annee;
    }

    public void setAnnee(String annee) {
        this.annee = annee;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public String getPrestation() {
        return this.prestation;
    }

    public void setPrestation(String prestation) {
        this.prestation = prestation;
    }

    public String getCouverture() {
        return this.couverture;
    }

    public void setCouverture(String couverture) {
        this.couverture = couverture;
    }

    public String getNomAy() {
        return this.nomAy;
    }

    public void setNomAy(String nomAy) {
        this.nomAy = nomAy;
    }

    public String getLien() {
        return this.lien;
    }

    public void setLien(String lien) {
        this.lien = lien;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public Long getAyantDroit() {
        return this.ayantDroit;
    }

    public void setAyantDroit(Long ayantDroit) {
        this.ayantDroit = ayantDroit;
    }

    public Long getMontantTotal() {
        return this.montantTotal;
    }

    public void setMontantTotal(Long montantTotal) {
        this.montantTotal = montantTotal;
    }

    public Long getMontantReglement() {
        return this.montantReglement;
    }

    public void setMontantReglement(Long montantReglement) {
        this.montantReglement = montantReglement;
    }

    public Long getMontantPaye() {
        return this.montantPaye;
    }

    public void setMontantPaye(Long montantPaye) {
        this.montantPaye = montantPaye;
    }

    public Long getIdStructure() {
        return this.idStructure;
    }

    public void setIdStructure(Long idStructure) {
        this.idStructure = idStructure;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VBonDeCommande (");

        sb.append(id);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(codeCarnet);
        sb.append(", ").append(idAdherent);
        sb.append(", ").append(matricule);
        sb.append(", ").append(refFacture);
        sb.append(", ").append(structure);
        sb.append(", ").append(datePayement);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(isConfirmedBon);
        sb.append(", ").append(whenConfirmedBon);
        sb.append(", ").append(annee);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(prestation);
        sb.append(", ").append(couverture);
        sb.append(", ").append(nomAy);
        sb.append(", ").append(lien);
        sb.append(", ").append(genre);
        sb.append(", ").append(ayantDroit);
        sb.append(", ").append(montantTotal);
        sb.append(", ").append(montantReglement);
        sb.append(", ").append(montantPaye);
        sb.append(", ").append(idStructure);

        sb.append(")");
        return sb.toString();
    }
}
