/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VNbrBonValider implements Serializable {

    private static final long serialVersionUID = 1386623741;

    private Long count;

    public VNbrBonValider() {}

    public VNbrBonValider(VNbrBonValider value) {
        this.count = value.count;
    }

    public VNbrBonValider(
        Long count
    ) {
        this.count = count;
    }

    public Long getCount() {
        return this.count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VNbrBonValider (");

        sb.append(count);

        sb.append(")");
        return sb.toString();
    }
}
