/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPharmacie implements Serializable {

    private static final long serialVersionUID = -1548227547;

    private Long      id;
    private String    libelle;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   isDeleted;
    private String    telephone;
    private String    statutStructure;
    private String    typeStructure;
    private Boolean   suspension;
    private String    region;

    public VPharmacie() {}

    public VPharmacie(VPharmacie value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.isDeleted = value.isDeleted;
        this.telephone = value.telephone;
        this.statutStructure = value.statutStructure;
        this.typeStructure = value.typeStructure;
        this.suspension = value.suspension;
        this.region = value.region;
    }

    public VPharmacie(
        Long      id,
        String    libelle,
        String    whoDone,
        Timestamp whenDone,
        Boolean   isDeleted,
        String    telephone,
        String    statutStructure,
        String    typeStructure,
        Boolean   suspension,
        String    region
    ) {
        this.id = id;
        this.libelle = libelle;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.isDeleted = isDeleted;
        this.telephone = telephone;
        this.statutStructure = statutStructure;
        this.typeStructure = typeStructure;
        this.suspension = suspension;
        this.region = region;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getStatutStructure() {
        return this.statutStructure;
    }

    public void setStatutStructure(String statutStructure) {
        this.statutStructure = statutStructure;
    }

    public String getTypeStructure() {
        return this.typeStructure;
    }

    public void setTypeStructure(String typeStructure) {
        this.typeStructure = typeStructure;
    }

    public Boolean getSuspension() {
        return this.suspension;
    }

    public void setSuspension(Boolean suspension) {
        this.suspension = suspension;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VPharmacie (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(telephone);
        sb.append(", ").append(statutStructure);
        sb.append(", ").append(typeStructure);
        sb.append(", ").append(suspension);
        sb.append(", ").append(region);

        sb.append(")");
        return sb.toString();
    }
}
