/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VReglementDetails implements Serializable {

    private static final long serialVersionUID = 753326709;

    private Long      id;
    private Long      reglement;
    private String    intitule;
    private Long      montant;
    private Long      quantite;
    private Long      prixUnitaire;
    private String    codeCarnet;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;
    private Timestamp lastUpdate;
    private String    refFacture;
    private String    typeReglement;
    private Long      idBon;
    private String    nomAd;
    private String    prenomAd;
    private String    matricule;
    private String    structure;
    private Long      tauxEffectif;
    private Timestamp datePayement;
    private String    prestation;
    private String    lien;
    private Boolean   isConfirmedBon;
    private Timestamp whenConfirmedBon;
    private Timestamp dateExpiration;
    private Long      totalCouvert;
    private Long      totalRestant;

    public VReglementDetails() {}

    public VReglementDetails(VReglementDetails value) {
        this.id = value.id;
        this.reglement = value.reglement;
        this.intitule = value.intitule;
        this.montant = value.montant;
        this.quantite = value.quantite;
        this.prixUnitaire = value.prixUnitaire;
        this.codeCarnet = value.codeCarnet;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
        this.lastUpdate = value.lastUpdate;
        this.refFacture = value.refFacture;
        this.typeReglement = value.typeReglement;
        this.idBon = value.idBon;
        this.nomAd = value.nomAd;
        this.prenomAd = value.prenomAd;
        this.matricule = value.matricule;
        this.structure = value.structure;
        this.tauxEffectif = value.tauxEffectif;
        this.datePayement = value.datePayement;
        this.prestation = value.prestation;
        this.lien = value.lien;
        this.isConfirmedBon = value.isConfirmedBon;
        this.whenConfirmedBon = value.whenConfirmedBon;
        this.dateExpiration = value.dateExpiration;
        this.totalCouvert = value.totalCouvert;
        this.totalRestant = value.totalRestant;
    }

    public VReglementDetails(
        Long      id,
        Long      reglement,
        String    intitule,
        Long      montant,
        Long      quantite,
        Long      prixUnitaire,
        String    codeCarnet,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted,
        Timestamp lastUpdate,
        String    refFacture,
        String    typeReglement,
        Long      idBon,
        String    nomAd,
        String    prenomAd,
        String    matricule,
        String    structure,
        Long      tauxEffectif,
        Timestamp datePayement,
        String    prestation,
        String    lien,
        Boolean   isConfirmedBon,
        Timestamp whenConfirmedBon,
        Timestamp dateExpiration,
        Long      totalCouvert,
        Long      totalRestant
    ) {
        this.id = id;
        this.reglement = reglement;
        this.intitule = intitule;
        this.montant = montant;
        this.quantite = quantite;
        this.prixUnitaire = prixUnitaire;
        this.codeCarnet = codeCarnet;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
        this.lastUpdate = lastUpdate;
        this.refFacture = refFacture;
        this.typeReglement = typeReglement;
        this.idBon = idBon;
        this.nomAd = nomAd;
        this.prenomAd = prenomAd;
        this.matricule = matricule;
        this.structure = structure;
        this.tauxEffectif = tauxEffectif;
        this.datePayement = datePayement;
        this.prestation = prestation;
        this.lien = lien;
        this.isConfirmedBon = isConfirmedBon;
        this.whenConfirmedBon = whenConfirmedBon;
        this.dateExpiration = dateExpiration;
        this.totalCouvert = totalCouvert;
        this.totalRestant = totalRestant;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getReglement() {
        return this.reglement;
    }

    public void setReglement(Long reglement) {
        this.reglement = reglement;
    }

    public String getIntitule() {
        return this.intitule;
    }

    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    public Long getQuantite() {
        return this.quantite;
    }

    public void setQuantite(Long quantite) {
        this.quantite = quantite;
    }

    public Long getPrixUnitaire() {
        return this.prixUnitaire;
    }

    public void setPrixUnitaire(Long prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }

    public String getCodeCarnet() {
        return this.codeCarnet;
    }

    public void setCodeCarnet(String codeCarnet) {
        this.codeCarnet = codeCarnet;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getRefFacture() {
        return this.refFacture;
    }

    public void setRefFacture(String refFacture) {
        this.refFacture = refFacture;
    }

    public String getTypeReglement() {
        return this.typeReglement;
    }

    public void setTypeReglement(String typeReglement) {
        this.typeReglement = typeReglement;
    }

    public Long getIdBon() {
        return this.idBon;
    }

    public void setIdBon(Long idBon) {
        this.idBon = idBon;
    }

    public String getNomAd() {
        return this.nomAd;
    }

    public void setNomAd(String nomAd) {
        this.nomAd = nomAd;
    }

    public String getPrenomAd() {
        return this.prenomAd;
    }

    public void setPrenomAd(String prenomAd) {
        this.prenomAd = prenomAd;
    }

    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    public String getStructure() {
        return this.structure;
    }

    public void setStructure(String structure) {
        this.structure = structure;
    }

    public Long getTauxEffectif() {
        return this.tauxEffectif;
    }

    public void setTauxEffectif(Long tauxEffectif) {
        this.tauxEffectif = tauxEffectif;
    }

    public Timestamp getDatePayement() {
        return this.datePayement;
    }

    public void setDatePayement(Timestamp datePayement) {
        this.datePayement = datePayement;
    }

    public String getPrestation() {
        return this.prestation;
    }

    public void setPrestation(String prestation) {
        this.prestation = prestation;
    }

    public String getLien() {
        return this.lien;
    }

    public void setLien(String lien) {
        this.lien = lien;
    }

    public Boolean getIsConfirmedBon() {
        return this.isConfirmedBon;
    }

    public void setIsConfirmedBon(Boolean isConfirmedBon) {
        this.isConfirmedBon = isConfirmedBon;
    }

    public Timestamp getWhenConfirmedBon() {
        return this.whenConfirmedBon;
    }

    public void setWhenConfirmedBon(Timestamp whenConfirmedBon) {
        this.whenConfirmedBon = whenConfirmedBon;
    }

    public Timestamp getDateExpiration() {
        return this.dateExpiration;
    }

    public void setDateExpiration(Timestamp dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    public Long getTotalCouvert() {
        return this.totalCouvert;
    }

    public void setTotalCouvert(Long totalCouvert) {
        this.totalCouvert = totalCouvert;
    }

    public Long getTotalRestant() {
        return this.totalRestant;
    }

    public void setTotalRestant(Long totalRestant) {
        this.totalRestant = totalRestant;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VReglementDetails (");

        sb.append(id);
        sb.append(", ").append(reglement);
        sb.append(", ").append(intitule);
        sb.append(", ").append(montant);
        sb.append(", ").append(quantite);
        sb.append(", ").append(prixUnitaire);
        sb.append(", ").append(codeCarnet);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(refFacture);
        sb.append(", ").append(typeReglement);
        sb.append(", ").append(idBon);
        sb.append(", ").append(nomAd);
        sb.append(", ").append(prenomAd);
        sb.append(", ").append(matricule);
        sb.append(", ").append(structure);
        sb.append(", ").append(tauxEffectif);
        sb.append(", ").append(datePayement);
        sb.append(", ").append(prestation);
        sb.append(", ").append(lien);
        sb.append(", ").append(isConfirmedBon);
        sb.append(", ").append(whenConfirmedBon);
        sb.append(", ").append(dateExpiration);
        sb.append(", ").append(totalCouvert);
        sb.append(", ").append(totalRestant);

        sb.append(")");
        return sb.toString();
    }
}
